### ISSUE TITLE
Can't add new participants after creating an event in Rally

### ISSUE THREAD

**Issue by 293652** [lukevella/Rallly#10]
Hi,

There doesn't seem to be an option to add new participants to an event after scheduling one in Rally. One of my colleagues didn't get an email after inviting him to the event, so i wanted to check if i entered his email address correctly, and if not, then resend his invite.

Could you let me know how this can be done?

Many thanks,
Caroline

**Comment by lukevella** [comment]
Hey Caroline, you can simply email the link to the event to your colleague. Just copy it from your address bar. Anyone with the link can access the event.

Hope this helps.
