### ISSUE TITLE
Email Signup not Accepting *.space addresses

### ISSUE THREAD

**Issue by KyleRConway** [lukevella/Rallly#100]
I have a *.space domain and the "schedule a new event" form's email field doesn't accept my email address as valid.

Would love to use my email here (example image attached). 

![Screenshot from 2021-10-19 15-58-11](https://user-images.githubusercontent.com/5899012/137989574-91b6e211-8c5b-4ebe-b353-989c1934f391.png)

**Comment by lukevella** [comment]
Thanks for raising. I've gone ahead and relaxed the validation on email address so this should pass now.
