### ISSUE TITLE
Docker: Building fails when activate SELF_HOSTED=true 

### ISSUE THREAD

**Issue by RichardHausgartner** [lukevella/rallly#1000]
**Describe the bug**
I compile rallly by myself because of the missing arm64 DockerHub image.
Till version 3.4.2 the build succeeded with activated `SELF_HOSTED=true`, but with latest commit it fails.

**To Reproduce**

1. `git pull` latest commit https://github.com/lukevella/rallly/commit/ba8c05fb5781494cd4f21e818400fa449e7afcea 
2. check that ` SELF_HOSTED=true` is set in `docker-compose.yml` 
3. do `docker compose build`
4. Building fails with this error:
```
88.91 @rallly/web:build: error Command failed with exit code 1.
88.98 @rallly/web:build: ERROR: command finished with error: command (/app/apps/web) yarn run build exited (1)
88.98 @rallly/web#build: command (/app/apps/web) yarn run build exited (1)
88.98
88.98  Tasks:    0 successful, 1 total
88.98 Cached:    0 cached, 1 total
88.98   Time:    1m28.17s
88.98 Failed:    @rallly/web#build
88.98
88.98  ERROR  run failed: command  exited (1)
89.02 error Command failed with exit code 1.
```

**Comment by mowtim** [comment]
Same here

**Comment by bmaster001** [comment]
I had a similar error, which I asked help for in the Discord channel. I got the answer "This channel/server is primarily intended for project contributions rather than seeking help with development issues.". Hope they want to take a look at this issue here!

**Comment by lukevella** [comment]
I think this could be related to https://github.com/lukevella/rallly/commit/47fb3b59d79e63074b0e89610e74d2a146d95075 and should be fixed now.
