### ISSUE TITLE
app.rallly.co  ≠ self hosted

### ISSUE THREAD

**Issue by SchBenedikt** [lukevella/rallly#1026]
It's not exactly a bug, but it's almost the right option.

I installed Rally and it works like this. But if I compare the official instance with my instance, then there is a sidebar on the left of the official instance that lists other tools that don't yet exist.

Is this the case with anyone else?
Unfortunately I didn't find any information about beta versions in the docs.

Thank you,
schBenedikt

**Comment by mowtim** [comment]
Same here. Seems to be a thing in the latest release.

**Comment by lukevella** [comment]
This is expected. Self-hosted releases don't happen as frequently so a bit of drift is expected. New things are tested on the managed service first where it's possible to debug and analyze before a self-hosted release is made. See [Official Docker Image](https://support.rallly.co/self-hosting/introduction#official-docker-image)

**Comment by SchBenedikt** [comment]
Yes, it looks the same now.
