### ISSUE TITLE
docker: reference to rallly_db should not contain port

### ISSUE THREAD

**Issue by tomquas** [lukevella/rallly#1079]
hi. since rallly_db in docker-compose.yaml is a service reference, it cannot contain a port number 

actual:
```
- DATABASE_URL=postgres://postgres:postgres@rallly_db:5450/db
```

result:
```
Prisma schema loaded from prisma/schema.prisma
...
Error: P1001: Can't reach database server at `rallly_db`:`5450`
```

fix:
```
- DATABASE_URL=postgres://postgres:postgres@rallly_db/db
```

result:
```
Applying migration `..._init`
```

https://github.com/lukevella/rallly/blame/fc9149a3b2fa4401a8331b6d849066b504ea15e2/docker-compose.yml#L31

**Comment by lukevella** [comment]
I believe this can be closed now.
