### ISSUE TITLE
One date instead of multiple dates?

### ISSUE THREAD

**Issue by amuselang** [lukevella/Rallly#108]
Is there a workaround to schedule an event using one date instead of multiple dates? Am interested in using the platform primarily for attendance at weekly event

**Comment by lukevella** [comment]
Hi @amuselang, that should be fine. Have you tried creating an event with one option? It should be possible already.

**Comment by amuselang** [comment]
I tried, but was not able to. A message popped up saying that I needed to enter another date.

**Comment by lukevella** [comment]
Any chance you could include a screenshot of this message?

**Comment by amuselang** [comment]
![image](https://user-images.githubusercontent.com/101789494/158804856-f6a4587b-7e2e-4634-af1a-6e09655afdad.png)

**Comment by lukevella** [comment]
You haven't actually selected any dates in that screenshot. The date highlighted in yellow is just today's date. Selected dates are shown in highlighted in green.

**Comment by amuselang** [comment]
Thanks, that worked. 
Questions: 

Is there an option to share the link directly with invited participants as a group instead of having the invitation sent directly to each participant individually? I tried the beta version and this is possible in the beta version but not the original version.

Is there an option to customize the text that the participants see in their invitation email in the original version? Instead of the text "Rallly is a free collaborative scheduling service,.....click on the dates that best suit you", the event scheduler can add information about the event or the text could be the same as the text in the Poll.

Is there an option to receive notifications when participants sign up?

Option to create a group email list?

Thx

Amy M. Lang |  412-952-1225    
***@***.***

**Comment by lukevella** [comment]
> Is there an option to share the link directly with invited participants as a group instead of having the invitation sent directly to each participant individually? I tried the beta version and this is possible in the beta version but not the original version.

The same is possible in the old version, you just need to copy the link from your browser's address bar. Anyone with a link to the page will have access to it.

> Is there an option to customize the text that the participants see in their invitation email in the original version? Instead of the text "Rallly is a free collaborative scheduling service,.....click on the dates that best suit you", the event scheduler can add information about the event or the text could be the same as the text in the Poll.

You can send the link to the event to your participants outside of Rallly, either by email, IM or any way you'd like. Sending out invites through the site is just there for convenience.

> Is there an option to receive notifications when participants sign up?

Yes, in the old version, if you have *Notifications* turned on you will receive an email whenever someone votes or comments on the event. You will need to verify your email address to get notifications. This setting can be turned on either when creating the event or you can edit the event and turn it on afterwards. 

There are no notifications in the new version yet but I'll add it at some point.

> Option to create a group email list?

Not at the moment. Maybe in the future but not sure when that will be.
