### ISSUE TITLE
Time zone detection yields wrong results

### ISSUE THREAD

**Issue by jbruechert** [lukevella/rallly#1081]
**Describe the bug**
My browser sends Europe/Berlin, but Rallly displays Europe/Busingen.
Practically there is probably no difference between these timezones, but it's definitely not the right one for Germany in general.

**To Reproduce**
1. Create poll
1. Enable times
1. See the default time zone

**Expected behavior**
It should display Europe/Berlin

**Screenshots**
![image](https://github.com/lukevella/rallly/assets/13609393/a58b3d2b-9e5c-43b9-8c98-dfb9d8864d51)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Firefox
- Version: 125.0.1

**Comment by lukevella** [comment]
Hi @jbruechert, I'll do my best to explain why this has happened and why I don't believe there is not an actionable issue:

In previous version of Rallly, your timezone would have been derived using the standard browser APIs. These APIs return an IANA timezone which can be location based (eg. Europe/Belgium) or it could be a fixed offset (eg. Etc/GMT+1).

There was an update that narrowed restricted the possible timezones to be location based only. For a scheduling app like Rallly, having a fixed offset timezone is not desirable.

What has likely happened is that your session was created in a version of Rallly where the fixed offset timezone was allowed, and when the updated was released the fixed offset was converted to the closest location based timezone.

I admit, the logic here was not ideal as is evident here and the migration may have been handled better with a more complex solution to ensure a more accurate location based timezone.

That said, I don't think there's anything that can be done. The timezone can be fixed through preferences and newer sessions will not have this problem. I apologize for the inconvenience.
