### ISSUE TITLE
Time-Ranges on Polls

### ISSUE THREAD

**Issue by UVAMedSchool** [lukevella/rallly#1097]
Hey there,

We use Rallly poll almost daily at the University of Virginia Med School for recruiting standardized patients to work for us.  Why oh why did you decide to discontinue putting the end-time on the polls??  This will not work for us because it will be too hard for people to understand that they have to point their cursor at the start-time to see the time-range for any given date.  Was this supposed to be an improvement?  

Please inform!  We love using your platform (and even pay for a subscription), but we will have to switch to a new product if this cannot be changed back to the way it was.

Thanks so much for your assistance!

Jerri Emm
SP Educator
Clinical Skills Center
University of Virginia School of Medicine
Charlottesville, VA
jae8x@virginia.edu

**Comment by lukevella** [comment]
Hi Jerri, sorry about the inconvenience this caused you. I'm happy to revert this change. It would help to understand a bit more why this is critical for your use case. Would it be fair to assume that you have options with different durations and that is why you need to show the end time? Perhaps your use case is not that of a scheduling poll where you are voting on a time to meet? It would help to understand how you are using Rallly as I plan to offer more solutions to offer a wider range of use cases.

**Comment by UVAMedSchool** [comment]
Hi Luke,

Thanks for your reply.  We do use it for scheduling in a few
different ways.  Often we have multi-day events and the participant
indicates which days/times they can participate (we're not just choosing
one date/time, but seeing who can work on which days and times).   We also
use it to schedule training and there are multiple choices on the same day
with different time options -- not always the same duration for each.

My main concern is that our contractors might not understand that they have
to put their cursors on the start time to see the duration of a certain
time slot.   I guess I just don't understand the advantage of *not *showing
the end-time like it used to?  Just makes sense to me that you would see
the whole time-range for each option.

We switched to using Rallly from Doodle after Doodle 'enhanced'
their product (I can't remember now what the change was) and we needed a
platform whose features better met our needs.  I guess change is hardest
when the benefit is unclear.

I hope that makes sense!

Thanks, again.

Jerri

**Comment by lukevella** [comment]
Could you let me know if it would be satisfactory for you to display the duration below the start time rather than the end time? My goal is to avoid confusion as showing multiple times vertically does not immediately communicate a time-range to everyone and can be confusing.

![CleanShot 2024-05-16 at 12 16 44@2x](https://github.com/lukevella/rallly/assets/676849/c90bb1ae-0e23-4977-bd61-49f2985e9acb)

**Comment by UVAMedSchool** [comment]
Hi Luke,

I guess if it shows the duration, then the time-range can be deduced, but
not sure what you mean by 'showing multiple times vertically?'  In the old
iteration (as you still show in your example poll, below) -- it shows the
choices horizontally across the page:

[image: Screenshot 2024-05-16 at 9.18.59 AM.png]

I really appreciate you trying to understand how we use the product and
what my concerns are.

Thank you for trying to help!

Jerri

**Comment by lukevella** [comment]
> not sure what you mean by 'showing multiple times vertically?'

I meant stacking the start and end time vertically like this:

```
08:00
09:00
```

It creates a lot of noise and makes it harder to read. I think showing the duration is a cleaner approach and has the added benefit of making it easy to spot options that have a different duration while still making it easy to deduce the end time.

That said, I will be working on more solutions along side scheduling polls that I believe will be more suitable for your use case such as Registration/Booking pages.

I will close this issue for now as beyond adding the duration  I don't plan to take further action for now but feel free to reopen if you feel more attention is needed here and thanks for raising this, your feedback was really helpful 🙏

**Comment by UVAMedSchool** [comment]
Thank you!  I appreciate you considering it.  I thought it worked fine the
way it was, but I can live with the duration -- it is a cleaner look!  :-)

Have a great weekend!
