### ISSUE TITLE
rallly polld

### ISSUE THREAD

**Issue by RichCPA** [lukevella/rallly#1147]
Completely perplexed. Just trying to use the free Rallly Poll feature and have questions. Was directed here, not to an e mail for support. Do not know open source. Help? Thsnks

See screenshot. Example of all This is all I see for results  richstreitfeld@gmail.com
![IMG_3212](https://github.com/lukevella/rallly/assets/172336328/b6e2fde2-15e9-4fbb-94cc-463620a89383)

**Comment by lukevella** [comment]
Hi @RichCPA, you can email support@rallly.co

I'm curious how you ended up on the Github repo looking for support so if you have any more information about that, please let me know.
