### ISSUE TITLE
Container does not work on multi-homed servers

### ISSUE THREAD

**Issue by gilgongo** [lukevella/rallly#1177]
**Describe the bug**
When running the Rallly container on a Docker host that has different network interfaces for SMTP and web applications, Rallly cannot send email.

**To Reproduce**

- Set up host with a web server and a mail server and two network interfaces `A` and `B`. Bind web to `A` and mail to `B`.
- Install and configure Rallly with `NEXT_PUBLIC_BASE_URL=[ip A]` and `SMTP_HOST=[ip B]`
- Go to Rallly web UI and input details to create an account, hit Submit. 
- No email is sent. Docker logs show timeout. 
- All outbound packets seem to be going to the web server's interface.

**Expected behavior**
The container's network configuration would allow mail to be sent through the interface that the mail server's host name resolves to. 

**Additional context**
I am running a self-hosted Discourse Docker image on the same machine, and that image sends out email without any issue using its network configuration.  The current Rallly configuration also works fine on a VM with a single IP for both web and mail.
 
Please also see discussion [thread here](https://github.com/lukevella/rallly/discussions/1092#discussioncomment-9859174).

**Comment by lukevella** [comment]
It sounds like you just need to customize your docker compose config. The config in [rallly-selfhosted](https://github.com/lukevella/rallly-selfhosted) is only a starting point and can and should be customized to suite your needs. If you believe the changes you need make sense to be pushed upstream then you can raise an issue or pull request in that repo.
