### ISSUE TITLE
German Locale

### ISSUE THREAD

**Issue by MichiFr** [lukevella/rallly#118]
Hi!

When intending to run the complete webpage in German language, is it sufficient to add a new "de"-subfolder below /public/locale/ and translate all texts from the "en"-subfolder into German language?

What about those AM/PM texts? Those are not available in any of those already available language files.

Thanks,
Michael

**Comment by lukevella** [comment]
Hi Michael, before this will be possible I will need to:

1. Add all missing text to the english locale (not all text is currently going through the localization API)
2. Add to choose locale by detecting it from the browser and allowing the user to change it manually
3. Use the previous step to set the locale for all dates and times.

It's in the roadmap but not ready yet. There are more critical things that need be finished before I get to this. Closing for now. If you'd like to discuss localization further please open a thread in the [discussions page](https://github.com/lukevella/rallly/discussions)
