### ISSUE TITLE
Add an option to avoid sharing participant emails in finalized calendar hit

### ISSUE THREAD

**Issue by charles-m-knox** [lukevella/rallly#1206]
As discussed in my PR #1205 , I want the ability to hide the list of attendees from the finalized calendar hit. I lead a few organizations and use Rally to gather consensus for 100+ people at times. My users have not consented to share their email with other users.

I implemented this successfully in #1205 and tested it, but it was closed by @lukevella on the grounds it doesn't fit his design parameters.

@lukevella please discuss your thoughts with me in this thread. Thank you

**Comment by lukevella** [comment]
Hi @charles-m-knox, I think if this were to be implemented it would make a lot more sense to be part of the Finalize dialog. I'm not sure how this can be effectively communicated to the user and this is the first time I'm hearing about such a request. You might be right about users wanting this but a single data-point is not enough to start investing time into something which I hope you will understand.

I'm moving this to discussions as it's not something that will likely be addressed soon.
