### ISSUE TITLE
Language is not global 

### ISSUE THREAD

**Issue by aquatic7** [lukevella/rallly#1222]
**Describe the bug**
Language changed to Danish in settings, but the site is in English for invited visitors. 

**To Reproduce**

1. Go to settings
2. Choose 'Dansk' as language 

**Expected behavior**
The site visitors end on for voting should be in danish. 

**Additional context**
Maybe the language change is only for my user. I'm not sure tho. 
If so this might not be a bug but maybe a feature request. 
When I'm logged in everything is in danish. But when I paste the invite link in a browser where I'm not logged in, then it's in English. 
Is it possible to make a site globally in a language and not just per user?

**Comment by lukevella** [comment]
By design, you cannot change another user's language preferences. The default language for each user is decided by their own OS or browser settings.
