### ISSUE TITLE
Make demo use the deployment URL

### ISSUE THREAD

**Issue by snaeil** [lukevella/rallly#131]
**Actual behaviour:**

The demo shows the following note:
> This poll has been automatically generated just for you! Feel free to try out all the different features and when you're ready, you can go to [rallly.co/new](https://rallly.co/new) to make a new poll.

**Requested behaviour:**

The deployment URL should be used instead:
> This poll has been automatically generated just for you! Feel free to try out all the different features and when you're ready, you can go to **[mydomain.com/new](https://mydomain.com/new)** to make a new poll.

**Reasons:**
* The users' intention is probably to stay on the current deployed site

**Comment by lukevella** [comment]
Fair point, will try to address this soon.
