### ISSUE TITLE
Docker image 3.10 not using localized email templates

### ISSUE THREAD

**Issue by qay21** [lukevella/rallly#1342]
**Bug description**
Using the official docker image (3.10 version), Rallly is sending emails with english content instead of the expected locale of the user interacting with the poll.

The creator's configured locale is French. The other test user answering the poll is also using the French locale. The poll was created after updating to 3.10 image. All emails are using english (poll creations, new answers, poll closure).

**Expected behavior**
I would expect the email to follow the logged user's configured locale, or maybe an app default locale if the user answering the poll is not logged in.

**Additional context**
I saw french translations on Crowdin (and will certainly contribute in the future) and 3.10 is properly running, so at this point I'm almost sure I'm missing a "locale" setting for the application somewhere, but I can't find any in the self-hosting doc. By advance sorry if opening this as a bug report is not accurate, I'm expecting a really obvious answer/config option that I totally missed on this point.

**Comment by lukevella** [comment]
Thanks for reporting. I'm looking into this.

**Comment by qay21** [comment]
Let me know if I can be of any help !

**Comment by lukevella** [comment]
This should be fixed in 3.10.1 but unfortunately it won't retroactively fix it for existing guest users. New guest users will have their preferred locale included in their session so they should receive emails in their preferred language.

**Comment by qay21** [comment]
Quick test, it is indeed apparently fixed. For SSO users, a logout is required for the locale to be properly handled, but other than that emails are now sent in the correct language.

Thanks !

**Comment by lukevella** [comment]
Thanks for confirming. I will (if I have time) release a fix to retroactively fix this for existing sessions but for now it will only work for new sessions since the problem was that the locale was not being set when a session was created.
