### ISSUE TITLE
Remember selected user

### ISSUE THREAD

**Issue by janru** [lukevella/rallly#135]
Hi @lukevella !

Great tool!
I'd like to use Rallly for my sports club where everyone votes multiple times a week in the same poll.
It would be great if the selected user is represented in the url (e.g. ?user=jan) so that one can save this link and the correct user is automatically selected to update the poll.
Sure, cookies would also be an option.

Best,
Jan

**Comment by lukevella** [comment]
Hi @janru there's already a discussion about this here: #124

I get what you mean with the URL but it's not a reliable enough solution I'm afraid as it doesn't stop anyone who wants to change someone else's votes from doing that.

**Comment by janru** [comment]
Hi @lukevella,
the issue is similar, but not the same.

- https://github.com/lukevella/rallly/discussions/124 is about preventing malicious users to edit others' votes.
- This issue is not about security, it's about convenience.

See our use case:

1. each member of the sports club needs to vote whether he/she attends a specific training slot.
2. No user is malicious, we prefer convenience over security
3. we prefer to change the poll via unprotected admin link (multiple trainers) or vote of sb. else (partner, kids,...)
4. Every member votes ~5 times per week. Voting should be quick via phone.

What we need:

It would be great if the selected user is represented in the url (e.g. ralllypoll.com/p/poll42?user=jan) so that one can save this link and the correct user is automatically selected to update the poll. Alternative: cookies. But that might be overkill.

Best, Jan
