### ISSUE TITLE
Link to blog in footer broken

### ISSUE THREAD

**Issue by pichichi91** [lukevella/rallly#136]
First of all, lovely product! 
I think this has some potential for this, even more with the changes from doodle since the lastest update and them trying to be more a calendly alternative.

Recurring/periodic group meeting has become really difficult there.

On another note, the link to the blog in the footer is broken. It probably used to be hosted on the same project? 
I can create a PR for this if you want

```html
<Link href="/blog">
  <a className="font-normal leading-loose text-gray-400 hover:text-gray-800 hover:no-underline">
    Blog
  </a>
</Link>
```

**Comment by lukevella** [comment]
Thanks for pointing out the broken link. I think recurring meetings is a common enough use so will definitely be addressing that soon. If you'd like to open a [discussion](https://github.com/lukevella/rallly/discussions) with your specific use case or any ideas in mind that would be helpful.
