### ISSUE TITLE
Vote options not visible on Firefox mobile

### ISSUE THREAD

**Issue by david-uhlig** [lukevella/rallly#1407]
**Describe the bug**
Vote option checkboxes are not visible on Firefox Mobile 131.0.3 on a Samsung Galaxy A52s 5G. Viewport size is 342x669 according to viewportsizer.com. Using FF mobile in landscape mode shows the checkboxes. Using Chrome on the same device also shows the checkboxes.

**Expected behavior**
The vote options checkboxes should always be visible.

**Screenshots**
![Screenshot_20241022_122258_Firefox](https://github.com/user-attachments/assets/fa0fb82d-d0ab-4416-87a3-7088d2a2ed45)

![Screenshot_20241022_122844_Firefox](https://github.com/user-attachments/assets/f2907c33-2345-49c3-a725-c22ad3051683)

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy A52s 5G
- OS: Android
- Browser Firefox Mobile 
- Version 131.0.3

**Comment by smncd** [comment]
Checked this out myself quickly, it seems like the combination of AM/PM/2h 30min and the fact that those elements are set to never shrink means the checkbox gets pushed out of the viewport.

**Comment by smncd** [comment]
Poked around with this a bit more, this could be fixed fairly easily by hiding the duration like you say @david-uhlig, something like this:

Modified file: apps/web/src/components/poll/mobile-poll/time-slot-option.tsx
```diff
   return (
     <PollOption {...rest}>
       <div className="flex items-center gap-x-4 text-sm">
         <div>{`${startTime} - ${endTime}`}</div>
-        
+        {((breakpoint === 'showDuration') || breakpoint !== 'showDuration' && !showVotes) && (
           <div className="flex items-center gap-x-1.5 opacity-50">
             <ClockIcon className="size-4" />
             {duration}
           </div>
-        
+        )}
       </div>
     </PollOption>
   );
```

The breakpoint here would be somewhere around 370 - 380 px.
