### ISSUE TITLE
Menu overflow with long names

### ISSUE THREAD

**Issue by iamericfletcher** [lukevella/rallly#1409]
**Describe the bug**
The 3 dot menu overflows the containing area for longer names

**To Reproduce**

1. Create new poll
2. Enter short and long names
3. Notice on the longer names an overflow as shown below

**Expected behavior**
3 dot menu within the container and not overflow into the selection area. 

**Screenshots**
![image](https://github.com/user-attachments/assets/44da00a2-ee92-4424-b6e4-5b08c4e12c2d)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version Version 130.0.6723.59 (Official Build) (64-bit)

**Comment by lukevella** [comment]
Hey @iamericfletcher, thanks a lot for reporting this. There's a fix on it's way!
