### ISSUE TITLE
[Bug] Participants not getting deleted correctly

### ISSUE THREAD

**Issue by sebiweise** [lukevella/rallly#1419]
**Describe the bug**
Participants not getting deleted correctly, the count of active participants is wrong on the dashboard.

**To Reproduce**
Add a participant
Delete a participant

**Expected behavior**
The number on the dashboard should only show the correct count of active participants excluding the deleted once.

**Screenshots**
![{7ABB174D-268D-40DF-BEA0-3F6C16519BB8}](https://github.com/user-attachments/assets/851261e2-4bd6-4f2c-930a-1d31a9386d3e)
But there are only 10 active participants.

**Desktop (please complete the following information):**

- OS: Windows
- Browser chrome

**Additional context**

**Comment by lukevella** [comment]
Thank you @sebiweise for reporting this issue. I have a fix incoming.
