### ISSUE TITLE
Saving entries

### ISSUE THREAD

**Issue by tommy1300** [lukevella/Rallly#15]
Some participants can't save their selections.  Are certain Web Browsers non-compatible?  Or is there another reason?

**Comment by lukevella** [comment]
All modern web browsers should be supported. 

Is it possible that the participants are not clicking the **Save** button after selecting their preferred dates?

**Comment by tommy1300** [comment]
Ok and thanks for coming back so quickly.  It might be because one participant had gone in again and saved a new line without leaving a name.  (Not sure how they managed it).  This was because when they went in again the couldn't see their original entry.  Not sure if I'm explaining this well!

**Comment by lukevella** [comment]
Closing this for now. If this is still an issue please reopen.
