### ISSUE TITLE
Compiling the jade templates

### ISSUE THREAD

**Issue by connor-t** [lukevella/Rallly#16]
How do I compile the jade templates into app.js?

Any changes I've made appear on my development machine but don't on my production server...
so I presume they get compiled in development but not production?

**Comment by lukevella** [comment]
Hey @connor-t. The jade templates should be handled by the jade npm package. As long as you have the package installed it should work. Did you run `npm install` on your production server?

**Comment by connor-t** [comment]
thanks, my problem was with deploying via capistrano
