### ISSUE TITLE
Creating new poll: error 500

### ISSUE THREAD

**Issue by monofox** [lukevella/rallly#166]
**Describe the bug**
Accessing http://localhost:3000/new is resulting in http error 500

Following error is produced:
```
rallly_1     | All migrations have been successfully applied.
rallly_1     | Done in 4.54s.
rallly_1     | yarn run v1.22.18
rallly_1     | $ next start
rallly_1     | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
rallly_1     | warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
rallly_1     | Error: iron-session: Bad usage. Minimum usage is const session = await getIronSession(req, res, { cookieName: "...", password: "...". Check the usage here: https://github.com/vvo/iron-session
rallly_1     |     at getIronSession (file:///usr/src/app/node_modules/iron-session/dist/index.mjs:19:11)
rallly_1     |     at nextGetServerSidePropsHandlerWrappedWithIronSession (/usr/src/app/.next/server/chunks/531.js:64:87)
rallly_1     |     at Object.renderToHTML (/usr/src/app/node_modules/next/dist/server/render.js:593:26)
rallly_1     |     at async doRender (/usr/src/app/node_modules/next/dist/server/base-server.js:878:38)
rallly_1     |     at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/usr/src/app/node_modules/next/dist/server/base-server.js:977:28)
rallly_1     |     at async /usr/src/app/node_modules/next/dist/server/response-cache.js:72:36
```

**To Reproduce**
1. git clone https://github.com/lukevella/rallly.git
2. cp sample.env .env
3. Update .env by setting `DATABASE_URL=postgres://postgres:postgres@rallly_db:5432/db` 
4. docker-compose up -d
5. Open browser, navigate to http://localhost:3000 and click on button "Get started"

**Expected behavior**
Site with form is opening in order to create a new poll

**Screenshots**
![image](https://user-images.githubusercontent.com/765309/167453447-8dadebbb-0ae5-4d3a-a860-61384e8382a0.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 98.0.1

**Smartphone (please complete the following information):**

**Additional context**

- Docker version 20.10.13, build a224086
- Debian 10.11

**Comment by monofox** [comment]
Upstream ticket: vvo/iron-session#498

**Comment by lukevella** [comment]
Hi, it looks like you're missing [`SECRET_PASSWORD`](https://github.com/lukevella/rallly#%EF%B8%8F-configuration) from your environment. I thought I added it to sample.env but must got reverted at some point before the latest update today. Should work if you just add that to your environment.

**Comment by monofox** [comment]
@lukevella: Confirmed its working, thank you very much. May it possible to update README and/or update the sample.env file? My thought was, that the sample.env contained all mandatory fields (some applications are generating the secrets on first docker start automatically).

**Comment by lukevella** [comment]
I just did. `SECRET_PASSWORD` is a new parameter I [added today](https://github.com/lukevella/rallly/pull/162. It was in the README already by I missed the `sample.env`. Thanks for raising this though and for confirming that it works now. Closing.
