### ISSUE TITLE
Docker container fails to build

### ISSUE THREAD

**Issue by 0x6b-dev** [lukevella/rallly#176]
**Describe the bug**
When building the docker container an error is produced:

```ERROR: Service 'rallly' failed to build : COPY failed: file not found in build context or excluded by .dockerignore: stat schema.prisma: file does not exist```

**To Reproduce**
As per install instructions.

**Comment by lukevella** [comment]
Hey there, thanks for pointing this out. I merged a change yesterday that moved the prisma schema and forgot to update the dockerfile. I've just merged a fix for this.
