### ISSUE TITLE
Docker: Creating Poll and View Demo not working

### ISSUE THREAD

**Issue by Daedalus3** [lukevella/rallly#178]
First: thanks for this cool project. Im running into a few issues though:

I'm trying to set up the docker image. When building the images, three errors appear:

1.
warning "react-hot-toast > goober@2.1.8" has unmet peer dependency "csstype@^3.0.10".
warning " > react-i18next@11.15.4" has unmet peer dependency "i18next@>= 19.0.0".

2.
"docker-compose up -d" was "error - ESLint must be installed in order to run during builds: yarn add --dev eslint

3.
The webpage shows, but when clicking on "View demo", only a message "Creating demo poll…" shows without really creating the demo.

When trying to set up a poll, I can get to the point where I'm able to click "Create poll", but nothing happens.

Anything I'm doing wrong or are there issues with the image?

Thanks!

**Comment by lukevella** [comment]
Hi, the warnings are fine shouldn't impact you in any way. With regards to (1) I just need to update some dependencies but this is inconsequential for you and with regards to (2) there's no point in running eslint during build so again, not so important.

If you can open up your browser dev tools and see if there are any errors in the console or network tab that would help with identifying your issue.

**Comment by Daedalus3** [comment]
Thank you for the very fast reply.

I checked the console and found that even when removing and rebuilding the docker image, the parameter NEXT_PUBLIC_BASE_URL I've set in the .env file is not being used, rallly is stuck to http://localhost:3000.

**Comment by lukevella** [comment]
Ok, I figured out what the problem is. This environment variables needs to be present during build time because they are injected into the bundle. I'm leaning towards running build as part of the command procedure since this will also solve #170 but need to have a proper think about whether this is the right thing to do. Will try and push a fix soon.

**Comment by lukevella** [comment]
This should be fixed now. Went a different route since building when running the image is not a great solution. Current solution makes it harder to distribute a prebuilt image but that's not happening yet so guess we'll cross that bridge when we get to it.

**Comment by blazekjan** [comment]
I am linking #186. Is it really fixed?

**Comment by max-tet** [comment]
Hi. Just to clarify: right now, it is not possible to build one image of Rallly and deploy it on multiple hosts each with a different domain name?

**Comment by lukevella** [comment]
Hi @max-tet, no that's not possible because the host name is injected into the bundle during build time. So you would need multiple builds (multiple images) to work with different hosts.

**Comment by haslersn** [comment]
> running build as part of the command procedure

I wanted to mention: This is a bad idea, because it prevents people from running the container on a read-only filesystem (for better security). Not sure whether read-only FS is currently supported, but running the build at runtime would prevent it long-term.
