### ISSUE TITLE
Unable to send email

### ISSUE THREAD

**Issue by 0x6b-dev** [lukevella/rallly#179]
**Describe the bug**
System is unable to send emails. Says "Uh oh! Something went wrong. The issue has been logged and we'll fix it as soon as possible. Please try again later." and logs nothing.

Where are the logs?

Can we just disable email outright? I don't want email.

**To Reproduce**
Try get the app to send an email.

**Additional context**
"Uh oh! Something went wrong. The issue has been logged and we'll fix it as soon as possible. Please try again later."

```SMTP_HOST=mail1.[hostname].me
SMTP_PORT=465
SMTP_SECURE=true

**Comment by lukevella** [comment]
If you don't want emails to be sent out you can remove all the env vars prefixed with `SMTP_`. I'm closing this issue since you haven't included any server logs to be able to debug this further.

**Comment by lukevella** [comment]
Also make sure you pull the latest changes, #178 may be relevant to the error that you are getting and I've only just pushed a fix for it.
