### ISSUE TITLE
Multiple day slots

### ISSUE THREAD

**Issue by ludoja** [lukevella/Rallly#18]
Would be nice to be able to support multiple days slots (e.g. by draging over calendar)

**Comment by kellyjisun** [comment]
bump

**Comment by mmoreshead** [comment]
bump

**Comment by doughnet** [comment]
Bump

**Comment by wilsse** [comment]
Is this an enhancement intended for the new version, currently in beta?

**Comment by heyakyra** [comment]
I feel this should stay open, especially as others will continue to go to solutions like LettuceMeet and WhenIsGood since it's simply unusable to try to provide the same flexibility and number of options using Rallly until it supports this.
