### ISSUE TITLE
The mongoose-shortid dependency is broken on node v0.12

### ISSUE THREAD

**Issue by Clemmy** [lukevella/Rallly#2]
As a result, npm install fails. See the issue here: https://github.com/jjwchoy/mongoose-shortid/issues/13

**Comment by lukevella** [comment]
I'm aware of this but haven't decided on a solution. I might try and figure out a fix for the mongoose-shortid issue or find an alternative but in the meantime you can use a node version manager and run the app using node 0.10. I'm using [tj/n](https://github.com/tj/n).
