### ISSUE TITLE
Email invalid error on alternate TLDs

### ISSUE THREAD

**Issue by ryangranzow** [lukevella/Rallly#21]
When using an alternate TLD, such as business.consulting, Rallly throws an errors, stating the email address (ex. email@business.consulting) is invalid. Appears there's QA logic on the email address format, but it is not recognizing alternate TLDs as valid. Please fix.

**Comment by nprail** [comment]
I was able to reproduce this issue. @lukevella A possible solution to this could be using [Mailgun's Email Validation API](https://www.mailgun.com/email-validation). 

I need a valid alternate TLD email address to test a solution, though. It checks MX records so even if it's a seemingly valid email address, it makes sure that emails can actually be sent to it.

**Comment by lukevella** [comment]
The new version of Rallly should handle this. Closing.
