### ISSUE TITLE
"500 Internal Server Error" with Nginx proxy manager #docker

### ISSUE THREAD

**Issue by deraljoscha** [lukevella/rallly#218]
So I have a rallly docker container up and running. I just followed the "Quickstart with docker" instructions. The rallly instance is running percetly fine on http://myserverip.com:3000

I'm using nginx proxy manager as a reverse proxy and within the .env I set "NEXT_PUBLIC_BASE_URL=https://rally.mydomain.com/"

I can access rallly just fine under http://myserverip.com:3000 but when I open https://rally.mydomain.com/ it gives me a "500 Internal Server Error"

Can you tell me what I did wrong?
thanks in advance

**Comment by lukevella** [comment]
Try removing the trailing slash from your base url. If you're getting a server error, have a look at the server logs.

For the future, please do not open issues to ask for help with your configuration. Use [Discussions](https://github.com/lukevella/rallly/discussions) instead.
