### ISSUE TITLE
Database authentication issues

### ISSUE THREAD

**Issue by Eirikr70** [lukevella/rallly#219]
Hello, now that I have an amd64 server, I am trying to install again rallly. But it fails on startup with the following messages
```
rallly     | Error: P1000: Authentication failed against database server at `rallly_db`, the provided database credentials for `postgres` are not valid.
rallly     | 
rallly     | Please make sure to provide valid database credentials for the database server at `rallly_db`.
rallly     | error Command failed with exit code 1.
```
And
```
rallly_db  | 2022-07-02 16:04:10.556 UTC [36] FATAL:  password authentication failed for user "postgres"
rallly_db  | 2022-07-02 16:04:10.556 UTC [36] DETAIL:  Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
```
I have set the database credentials at
`      - POSTGRES_PASSWORD=postgres`

**Comment by lukevella** [comment]
No idea. You must be providing the wrong auth details somehow but you haven't provided enough info to figure out how you're doing that. Please don't open an issue for problems with your particular configuration. Use discussions instead.

**Comment by Eirikr70** [comment]
Sorry, I had failed the first install, and not removed the volume when trying again.
