### ISSUE TITLE
Different days seen by people in different timezones?

### ISSUE THREAD

**Issue by magaronov** [lukevella/Rallly#22]
I am in CST, and a friend of mine is in PST. When I create an event and add days, all of his day options are a full day "back" from what I'm saying. That is -- if I pick Thursday, Friday, Saturday, Sunday, he will instead see options for: Wednesday, Thursday, Friday, Saturday.

I'll try to recreate the event & see if that fixes it, but wanted to note this before I forgot!

**Comment by avoidik** [comment]
Guys, no timezones still?

**Comment by egcohen** [comment]
Still hasn't been fixed. It looks like this gets reported about once a year, so I'm reporting it again...

**Comment by VoiceScientist** [comment]
Happened to me too after scheduling a meeting with a dozen people across 4 time zones. Major headache. I really like the Rally interface, but if it shows different days across different time zones, it is completely unusable for me.

**Comment by lukevella** [comment]
Hi all, sorry for the silence. Unfortunately I wasn't able to spare the time to fix this in the current version of Rallly but I'm working on a new version at the moment and this will definitely be addressed. Thanks for bringing this to my attention.
