### ISSUE TITLE
End time dropdown list can become unusable

### ISSUE THREAD

**Issue by robtree** [lukevella/rallly#221]
**Steps to reproduce the behavior:**
1. Go to New Poll (step 2 of 3)
2. Pick a date and specify 7.30pm - 10.00pm
3. Pick a second date and select 11.30pm from the start time dropdown list
4. Open the second date's end time dropdown list (labelled 2:00 AM, as it's picked up the previous 2h30 duration)

**Expected behavior**
Time options should be visible in the end time dropdown list.

**Observed behavior**
It's not possible to pick any options from the end time dropdown list until the start time is brought back to 9.15pm.

**Screenshots**
![image](https://user-images.githubusercontent.com/3150192/177419435-e740925b-0f8e-4836-9972-fb55d9f65289.png)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Chrome
 - Version: 103.0.5060.114 (Official Build) (64-bit)

**Comment by lukevella** [comment]
Thanks for reporting. I will be addressing this soon with an update on this component.
