### ISSUE TITLE
Unable to change time zone for an existing poll

### ISSUE THREAD

**Issue by johann-petrak** [lukevella/rallly#222]
Created a poll and used the default time zone.

When I realized my mistake, wanted to change the time zone, but clicking "Manage" - "Edito Options", then choosing the correct time zone from the dropdown menu. However, when the tz is chosen, the whole edit dialog gets dismissed immediately (so no chance to click Save) and the time zone is not actually changed at all.

**Comment by johann-petrak** [comment]
This still does not work properly though: when I change the timezone, the times get changed in the shared view (the original time gets mapped to the time in the new timezine), but in the edit dialog, the OLD time is still shown. 
In my case, I used the wrong time zone but entered the correct times for what would have been the correct time zone, so changing the time zone should NOT change the times shown in the shared view. 
However even if changing the time zone should adapt the times, then it should ALSO adapt the times in the dialog, which it does not do either.

**Comment by lukevella** [comment]
Hi Johann, when looking at the poll options times are automatically adjusted to your current time zone. Participants can change this using the time zone picker on the poll page. To see the original times entered by the administrator you can select “Ignore time zone”. If you as the admin want everyone to see the same times regardless of what time zone they are in then you can edit the options and choose “Ignore time zone” which removes the option the adjust the time zone for participants.

**Comment by johann-petrak** [comment]
Thanks, ignore time zone is probably the best solution for my case.
