### ISSUE TITLE
Let attendee add additional date/time?

### ISSUE THREAD

**Issue by xjlin0** [lukevella/Rallly#25]
Hi Luke,

It's a great work and I like it, so happy to see your coming revision!

One suggestion:  In addition to let meeting creator defined the date(time), is it possible to allow attendee add additional date(time)?

Thanks a lot and have a wonderful 2017!

**Comment by gaia** [comment]
Please see issue #4 and fold this into it.

**Comment by lukevella** [comment]
Duplicate of #4. Closing.
