### ISSUE TITLE
Optimize Self Hosted & Other Improvements

### ISSUE THREAD

**Issue by nprail** [lukevella/Rallly#29]
Simply put, this does not work out of the box when self hosted. It is VERY specific to Rallly.co and some changes need to be made. Here are some of the things I found:

### Self Hosting Optimization
- [x] The from email address is hard coded to noreply@rallly.co (should be set in `config/main.js`)
- [x] The from name is hard coded to Rallly (also should be set it `config/main.js`)
- [x] Docker/docker-compose support: Containers are all the rage these days. This would be nice for a quick setup of Rallly. 
- [x] Better installation instructions. I had to jump through quite a few hoops to get it running in the first place. There is no docs on how MongoDB should be configured or how to keep Rallly running (e.g. with [Forever](https://www.npmjs.com/package/forever). 
- [x] While there is the ability to set your own SendGrid API key, it doesn't actually work because it references a SendGrid email template which is SendGrid account based. The template ID should also not be hard coded. The creation of a SendGrid template should be documented. 
### General Improvements/Feature Ideas
- Moved to #31
### [Rallly.co](http://rallly.co) Cloud Hosted Service
- Moved to #30 

I can definitely help with some of this. I've got a decent amount of MEAN (minus mongo) experience. Be expecting some PRs. 

I love the idea of this software and I would love to use it but it needs a little work as all software does. 😉

**Comment by lukevella** [comment]
Hey @nprail, thanks for writing this up. You're right, Rallly in it's current state is not optimized to be self hosted. Unfortunately my availability is very limited, which means I'm not really able to sufficiently offer support for this project and I don't know if and when this will change. Of course you're free to use and modify the source as you wish, and feel free to ask if you have any questions.

**Comment by nprail** [comment]
@lukevella Awesome! 

I'm going to move some of these tasks to their own issues to keep discussion from being cluttered with quite a few different things. As you can see, I already added some new config options. I'm unable to test them, though, because I don't know how to configure the SendGrid template.

**Comment by nprail** [comment]
@lukevella What is the license type? It doesn't directly say but it looks like it's a version of the Creative Commons license. Which version is it?

**Comment by nprail** [comment]
@lukevella What do you think about using [nodemailer](https://nodemailer.com/about/) instead of only SendGrid?

**Comment by nprail** [comment]
@lukevella Be expecting a PR soon with self hosting improvements. I've done almost everything in this issue.
