### ISSUE TITLE
General Improvements/Feature Ideas

### ISSUE THREAD

**Issue by nprail** [lukevella/Rallly#31]
These are just a few improvement and feature ideas moved from #29.
### Improvements
- [ ] Ability to add attendees after the initial creation of event. 
- [ ] Option to add an email address in an attendees response so an email can be sent to them with the final date decision. 
### Feature Ideas
- [ ] Some sort of authentication. At least a password for editing the details since anyone can edit the event. 
- [ ] Option to set a password for the event. It would be good if there could be one password that you share with all the attendees so that a private event can be just that. Private.

**Comment by nprail** [comment]
@lukevella I'm going to start working on some of these ideas. I think I'll start with adding an option to put a password on events.

**Comment by lukevella** [comment]
Hey Noah, I really don't have time to review large changes to the codebase right now. It doesn't seem like I will for some time. Sorry.
