### ISSUE TITLE
Which branch is considered for production use?

### ISSUE THREAD

**Issue by luclu** [lukevella/rallly#317]
Hello,

I'm currently in the [progress of adding](https://github.com/onedr0p/containers/pull/67) rallly to https://github.com/onedr0p/containers.
This repo will use config files to automize the build process of docker container images on Github's infrastructure and publish them under https://github.com/onedr0p?tab=packages&repo_name=containers for public use.

Could you kindly point out which branch is considered stable and graded toward production use?
Is the `production` branch the correct choice or should I select `main` instead?

Thank you for your answer and your great project!

**Comment by lukevella** [comment]
Hi @luclu. The `main` branch is considered production and is what's available on rallly.co. 

The `production` branch is just used to test feature branches with the production environment so that can be ignored.

Hope that answers your question.
