### ISSUE TITLE
Hard coded english text

### ISSUE THREAD

**Issue by daunera** [lukevella/rallly#324]
https://github.com/lukevella/rallly/blob/2c6f64bdc3e69a7329420754034d85ed5ac2e783/src/components/standard-layout.tsx#L205

"Your profile" is not a translatable text. It would be great if this text was included among the localizable texts

**Comment by lukevella** [comment]
Thanks @daunera, fixing this shortly.

**Comment by daunera** [comment]
Thanks, appreciate it
