### ISSUE TITLE
[Feature Idea] Mobile App

### ISSUE THREAD

**Issue by nprail** [lukevella/Rallly#35]
Here is an idea! Build a Rallly mobile app! Since it is built with MEAN, this could be easily accomplished with [Ionic](https://ionicframework.com)/[Cordova](https://cordova.apache.org). I've built a few Ionic apps so I could do this myself.

**Comment by lukevella** [comment]
It's not something that I plan to do. I would prefer to invest the time to make it work better on a mobile browser rather than porting to an app. Closing, but feel free to reopen if there's anything you want to discuss on this topic.

**Comment by nprail** [comment]
Maybe a whole app is too much but PWA support at least would be great. That would make it _almost_ as good as a native app.
