### ISSUE TITLE
Check for unused i18n keys

### ISSUE THREAD

**Issue by lukevella** [lukevella/rallly#354]
We need a script to automatically detect (and remove) unused i18n keys.  Consider using [i18n-unsued](https://www.npmjs.com/package/i18n-unused) to help with this.

If anyone is interested in helping with this issue please let me know.

**Comment by tinsaye** [comment]
Hey  @lukevella, I have been using rallly for a couple of weeks and linking it so far. So I would like to contribute back :)

I have already taken a glance at [i18n-unsued](https://www.npmjs.com/package/i18n-unused) . The tool allows displaying and removing unused keys with just 2-3 commands. When running it on the main branch, it reports `Total unused translations count: 2427`.

When do you wish it to be run?

**Comment by lukevella** [comment]
Hi @tinsaye, to start it would be great to just have a script that can be executed manually through yarn. Something like:

```
yarn lint:i18n
```

> it reports Total unused translations count: 2427

That number seems high considering there aren't even that many unique i18n keys. Might be worth double-checking what it's reporting.

**Comment by tinsaye** [comment]
Sounds good.

> That number seems high considering there aren't even that many unique i18n keys. Might be worth double-checking what it's reporting.
Ah sorry, should have mentioned that the count is all languages combined. Unique keys are about 150.
