### ISSUE TITLE
Rallly not accessible to people with visual imparements

### ISSUE THREAD

**Issue by gene1wood** [lukevella/rallly#365]
**Describe the bug**

I shared a rallly poll with some colleagues and one of my colleagues who has a visual impairment wasn't able to fill out the form to indicate their availability. They could see what the days and times were but couldn't interact with the form.

**To Reproduce**

The page linked below has good guidance on how to determine if your service is accessible to those with visual impairments

https://www.siteimprove.com/glossary/screen-reader-testing/

Easiest would likely be to just download a screen reader and try to use Rallly as a participant, trying to fill in their availability.

**Expected behavior**

Ideally people with disabilities would be able to participate in Rallly polls.

The W3C has a good summary of why this matters : https://www.w3.org/WAI/fundamentals/accessibility-intro/#important

**Comment by lukevella** [comment]
Hi @gene1wood, I understand this is a problem and it's already covered in #306. I do plan on improving accessibility but it will be after the next major release which I am currently working on. I'll close this since there is already another issue.
