### ISSUE TITLE
Unble to login as not guest

### ISSUE THREAD

**Issue by Nobu1225** [lukevella/rallly#368]
**Describe the bug**
Unable to login as user after recieved the magick link and press "Log me in" in the mail, displayes as "Guest". It's not displayed  registered name (left part of "@" of email address) and "user" like behavior on your page.
I am sorry if I have mis-configuration but it would be appreciated it if you can help me.

**To Reproduce**
1. Presss "login", add the email address and then submit it
2. Click on "Log me in"
3. Displayes new poll screen but user name is indicating "user-****" with guest

**Expected behavior**
Displayes user portal and change the displayed name from guest to name of user

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: [CentOS8, running under NGINX with proxy settings of starndard function of NGINX)]
 - Browser [Chrome]

Best regards
Nobuyoshi

**Comment by lukevella** [comment]
Hi @Nobu1225, please look at the network requests in your browser to see if anything is failing during login and look at the server logs from the docker image to see if any error is being reported.

**Comment by Nobu1225** [comment]
Thanks for reply, I have checked. It is not the bug, please forgive me.
It seems something information such as session or parameter fowarding was missing between NGINX and Rallly.
I will keep investigation for this perspective.
Thanks for your support.

**Comment by lukevella** [comment]
No problem. I'll go ahead and close this then.
