### ISSUE TITLE
iOS: Scrolling doesn't hide navigation bars

### ISSUE THREAD

**Issue by vollkorntomate** [lukevella/rallly#377]
**Describe the bug**
When viewing Rallly on iOS (tested on Safari and Firefox, both behave equally), scrolling doesn't hide the navigation bar as it usually does on most websites. Additionally, iOS's tap-to-top feature (tapping at the top of the screen scrolls all the way to the top) doesn't work, i.e. tapping the top doesn't do anything.

I suspect the issue is somewhere with scrolling and the JavaScript framework used. I've seen this behavior before in some other websites.

**To Reproduce**
1. Open Safari or Firefox on iOS
2. Go to any Rallly instance
3. Scroll down
4. The navigation bar on the bottom doesn't retract
5. Tap the top of the screen
6. Page doesn't scroll to the top

**Expected behavior**
In point 4, the navigation bar is expected to retract
In point 6, the page is expected to scroll to the top

**Smartphone (please complete the following information):**
 - Device: (mostly) iPhone
 - OS: iOS 16.2 (latest)
 - Browser: Safari, Firefox

Thanks for this amazing tool, I love using it nonetheless! Way better than any of the proprietary and open-source competitors.

**Comment by lukevella** [comment]
Hi @vollkorntomate, thanks for raising this. Will deploy a fix for this soon.
