### ISSUE TITLE
You can change selections of OTHER partipitants ???

### ISSUE THREAD

**Issue by rwhfdha** [lukevella/Rallly#38]
It looks to me as if **ANY** participant can change the selections of any **OTHER** participant.....Is that how this thing works? 

Before Rallly can compete with the likes of Doodle, this ability to change OTHER partipitant's selections will have to be fixed, right?

**Comment by lukevella** [comment]
Rallly's is a tool to be used amongst friends and the expectation is that participants work together towards a common goal. There's no need to restrict people and add extra steps to the process to authorize each participant.

Closing.
