### ISSUE TITLE
Ability to indicate time availability

### ISSUE THREAD

**Issue by kevinrabinovich** [lukevella/Rallly#4]

**Comment by joejohnsonlive** [comment]
+1 for this feature
Luke, it is a beautiful and intuitive app.  Time windows (or even just start time) would really finish off the simple task it enables.

**Comment by hanswundersam** [comment]
Another +1! Being able to provide meeting times in addition to dates looks like a crucial feature to me. Thanks Luke for this beautiful piece of software!

**Comment by cvonkleist** [comment]
I'd be very excited to see this feature. For me, this would take Rallly from a nice-to-have to a must-have.

**Comment by lukevella** [comment]
Hey everyone, thanks for the feedback and sorry I haven't been able to dedicate enough time to deliver this feature yet. I just want to assure you that it is on my radar and I will be working towards implementing this as soon as possible.

Thanks for your patience.

**Comment by jysimon** [comment]
+1 for this feature, quite important in business environments.

**Comment by dwitkin** [comment]
+1 for this. Right now, the app looks great but wouldn't be usable for me without the ability to select time slots.

**Comment by Katalonian** [comment]
It's great app, but without this feature there is no use for me.

**Comment by doughnet** [comment]
Agreed. Kind of worthless without time scheduling.

**Comment by thehowellsgroup** [comment]
Yes! This app would be SO much more useful if we could add time slots to it, or attach times to the dates we are suggesting. 
Thank you so much for the rallly site and service, I would use consistently and recommend to others if it had a time feature.

**Comment by pge** [comment]
Hi Luke. Great tool. It's been some time. What's the status on the time-slot feature?

**Comment by madslundholmdk** [comment]
@lukevella what is the status of this?

**Comment by Yelles** [comment]
would love that too !
The only thing that prevents me from using this tool is that I can not specify time slots per day.

**Comment by MichiFr** [comment]
H! Thanks for this helpful tool! 

Guess what? I would like to see time dependent day selections, too. Which means the ability to add several time point each single day, the attendee can select of. Just like e.g. Framadate is capable of.

Cheers,
Michael

**Comment by jonyzambrano01** [comment]
+ 1!

**Comment by lukevella** [comment]
Ok so it took a bit longer than expected but it's done now :) Closing.
