### ISSUE TITLE
Don't use Google Fonts

### ISSUE THREAD

**Issue by colfes** [lukevella/rallly#404]
**Describe the bug**
Rallly uses Google Fonts, and issues requests to fonts.gstatic.com.
This is illegal in most of Europa and can lead to fines.
It would be much, much better if Rallly served these fonts itself.
(There is no problem with the fonts itself.)

**To Reproduce**
From the docker version of Rallly, go to the landing page and watch network analysis in the browser of your choice.

**Expected behavior**
Fonts are bundled in with Rallly and served from your own server; no requests that leak your IP to Google are made.

**Additional context**
Using Google Fonts has lead to some trouble (including lawsuits/fines) for people running websites that use them without prior consent.
This can be a GDPR violation. So right now, it is questionable if running Rallly in Europe or for European users is legal.

**Comment by colfes** [comment]
Hi, just a quick follow-up: Thanks a lot for fixing this so quickly! Unfortunately, the container currently at dockerhub (lukevella/rallly) still uses google fonts, even though dockerhub shows it is just 2 days old. I quickly built the container myself, and it doen't use google fonts there. Maybe you could push the fix also to dockerhub (at your convenience), then I don't have to build myself :)

**Comment by lukevella** [comment]
Are you sure you pulled the latest image from docker hub?

**Comment by colfes** [comment]
Yeah I did, but probably browser cache or something. Works fine now :). Sorry 🙃
