### ISSUE TITLE
Addition Request: specify time and/or comment on each option of dates

### ISSUE THREAD

**Issue by csaksena** [lukevella/Rallly#48]
I really appreciate the good UI and appearance. It's super easy to use. One addition which would make Rally more appealing to a wider audience is an option of distinguishing time of day for each of the options. Another suggestion is adding the ability to comment on each individual option selection (ie for informing of specific conditionals not applicable to the total data set).

Thanks!

**Comment by thekyriarchy** [comment]
Agreed, the UI is beautiful, and nothing yet is available that ha such a nice interface that can schedule times of day

**Comment by JMPTon80** [comment]
This is a simple elegant site and works well. 

However I Agree AaTime Picker option is critical for wider adoption. 

You also may consider the ability stack rank or weight rank Date and Time options as well. Less need for discussion and the data and time can be driven by a user input rating.
