### ISSUE TITLE
Google Calendar Integration

### ISSUE THREAD

**Issue by ysorochan** [lukevella/rallly#49]
Would be nice to have integration with google calendar.

**Comment by jpellegrini** [comment]
If possible, it would be nice to be able to sync with other calendars also. For example, I use NextCloud, not Google Calendar.

**Comment by lukevella** [comment]
I will try to add this in the future but trying to focus my efforts on what can be done immediately at the moment. Closing.

**Comment by kbzowski** [comment]
@lukevella May I suggest that this issue be left open. It is possible that someone will want to implement such functionality if they see that there is a demand.

**Comment by polhenarejos** [comment]
Is there any progress on it?
