### ISSUE TITLE
AD/Ldap Integration

### ISSUE THREAD

**Issue by bganchev** [lukevella/Rallly#5]
Hello,

Awesome work on this one. It will be fantastic if a feature like LDAP (Active Directory) implementation is developed. 
What do you think about it?

Bobby

**Comment by lukevella** [comment]
Not sure how that would fit in to the product? Could you provide some more details?

**Comment by bganchev** [comment]
Hi,

there is no alternative software out there to attend event with your Active Directory credentials. 
In large companies there are many solutions but none of them is simple as that. 
The simple idea is instead of sending invitations in Outlook, etc, you send an e-mail with the link to event. Each employee enters his domain credentials (account is created if it is not already) and he just check if he's coming or not. 
Even better functionality will be if you can import the users from particular OU's of Active Directory.
Whoever organize event, he can select to invite all the users and in the end he'll have the complete list of attenders.

Bobby
