### ISSUE TITLE
Missing German translation - 100% translation progress on Crowdin

### ISSUE THREAD

**Issue by Cryotize** [lukevella/rallly#520]
**Describe the bug**
When creating a new Meeting, the "Ignore time zone" field won't switch to a German translation when selecting German as the display language. I've already checked if the translation is missing on Crowdin, but i cannot find this specific text and the translation progress is at 100%.

**To Reproduce**
1. Open the Website, click on "Get started"
2. Fill in all fields, then "Continue" 
3. Go to "Preferences" -> "Language" -> "German"
4. Check time zone field, which is still in english

**Expected behavior**
It should display "Zeitzone ignorieren" instead of "Ignore time zone"

**Screenshots**
![Screenshot from 2023-02-23 22-57-27](https://user-images.githubusercontent.com/49732602/221041242-395f3489-ab9d-46a1-8cc9-653d01d6eda5.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 110

**Comment by nvi9** [comment]
It is the default option of the timezone dropdown and all options are in English currently (see [time-zones.json](https://github.com/lukevella/rallly/blob/main/apps/web/src/components/time-zone-picker/time-zones.json)). It would be nice to make localizable these together, not just the "Ignore time zone" option.

**Comment by lukevella** [comment]
I'm aware this component is not currently translatable so this is not a language specific issue.

The reason why I'm not asking to translate the current list of time zones is because I will revise this component very soon and I don't want to over-burden translators. So closing this for now and I'll address it in a future up.
