### ISSUE TITLE
app crash when adding time slot at the end of a day

### ISSUE THREAD

**Issue by jonas-hoebenreich** [lukevella/rallly#530]
**Describe the bug**
When you try to specify a time slot at the end of the day in week view, the application crashes.

**To Reproduce**
1. Create new poll
2. Switch to week view
3. Add new time slot at the end of the day

**Expected behavior**
Application does not crash

**Screenshots**
https://user-images.githubusercontent.com/64426524/221411502-3d7a448c-ad03-45eb-be0f-9f79708ec37b.mp4

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox & chrome
 - Version: latest

**Additional context**
This commit fixes the bug: https://github.com/jonas-hoebenreich/rallly/commit/b191214af90be10a2db73496882e0c247c912749
But it's still not possible to add a new time slot at the end of a day (after all, the end is 12am the next day and the time slot is simply not added) Should I anyway open a pull request?

**Comment by lukevella** [comment]
Hi @jonas-hoebenreich, yes feel free to open a PR to fix this issue.

Currently we extend the nextjs instance in [dayjs.tsx](https://github.com/lukevella/rallly/blob/main/apps/web/src/utils/dayjs.tsx#L130-L138) so it might be worth doing the `.extend()` call there for the sake of consistency.
