### ISSUE TITLE
Missing Translation for Email Verification and Notification

### ISSUE THREAD

**Issue by MrMuster** [lukevella/rallly#543]
**Describe the bug**
The verification and notification emails are not translated.

**To Reproduce**
1. Preferences -> Language: German
2. Create new Account / Create new poll
3. Receive email in English

**Expected behavior**
The email should be translated to the selected language.

**Desktop:**
 - Browser Firefox
 - Version: 102 ESR

**Additional context**
Rallly version: 2.2.3

**Comment by lukevella** [comment]
I'm aware of this issue. Until recently this would have been quite difficult to solve but we're getting closer to a solution. I've opened #547 which will track this issue and I'll go ahead and close this one.
