### ISSUE TITLE
Create heartbeat workflow

### ISSUE THREAD

**Issue by lukevella** [lukevella/rallly#570]
It would be quite useful to have a workflow that we can run that run some e2e tests against the production environment at https://rallly.co

## What we need

Create a new app in the `apps` directory called `heartbeat-test`. The package name should be `@rallly/heartbeat-test`.

The app should use playwright to run e2e tests. As a starter, right a test that accesses the `/demo` path and expects the page to load correctly (e.g. check the title of the poll).

We should be able to configure playwright's `baseUrl` with an environment variable.

Once we have the app we can create a github workflow that runs the heartbeat test ever hour against prod. The workflow should send a notification if the tests fail.

<sub>[RAL-270](https://linear.app/rallly/issue/RAL-270/create-heartbeat-workflow)</sub>

**Comment by kleenkanteen** [comment]
Is rallly a monerepo? Inside the `apps` folder I see 3 folders, each with their own tsconfig.json and next.config.js.

**Comment by lukevella** [comment]
Hi @kleenkanteen, to answer your questions: 

> Is rallly a monorepo

Yes, this is a monorepo, more specifically a [turbo repo](https://turbo.build/).

> Do I create a new app using the next.js cli?

No, there's no need for that in this task. You need to use [playwright](https://playwright.dev). That said, this might not be a suitable task if you've not used it before.

With regards to that error, I'm not sure as I can't reproduce it. Perhaps you're using a different TypeScript version. Try and use the workspace version and if the issue persists open a separate issue since it's not related to this task.

**Comment by LeviAdamMiller** [comment]
Working on this issue with @jackle500 and @rjtrenchard.

**Comment by rjtrenchard** [comment]
Hello @lukevella! 
What is meant by the `/demo` path? Do we create a page that routes there? Does it already exist?
