### ISSUE TITLE
Portuguese (Portugal) not detected and goes to Portuguese (Brasil)

### ISSUE THREAD

**Issue by famaia** [lukevella/rallly#576]
**Describe the bug**
Rallly seems to be unable to detect Portuguese (Portugal) language on browser (Edge or Chrome) and goes to Portuguese (Brasil) instead.

**To Reproduce**
1. Open Rallly with Edge or Chrome with Portuguese (Portugal) language by default
![image](https://user-images.githubusercontent.com/736407/225982957-3ead8992-dcd6-4228-9098-19e9010b56b9.png)

3. Click on 'Preferences'
![image](https://user-images.githubusercontent.com/736407/225983232-e1859d12-2bb8-4dc3-82fe-3d530eb3b32f.png)

6. See wrong language selected by default.

**Expected behavior**
Right language should be selected

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Edge
 - Version Latest

**Comment by lukevella** [comment]
Hi, thanks for raising this. I managed to reproduce it. Will try to get a fix out in the next release.

**Comment by famaia** [comment]
That was fast :-) thank you.

I also think there are some strings to be translated, can I help with this?

And, unrelated, what does this SECRET_PASSWORD enviroment variable on docker? Is there any hidden admin menu (i don't know any) or is this just for data encryption purposes?

**Comment by lukevella** [comment]
It'd be really great if you can help with translation @famaia. We have a project on [Crowdin](https://crowdin.com/project/rallly/invite?h=6ca4f5a5762e7c12d50b7266579d29b31641745) where you can submit translations. Also this [guide](https://github.com/lukevella/rallly/wiki/Guide-for-translators) will be useful.

> And, unrelated, what does this SECRET_PASSWORD enviroment variable on docker? Is there any hidden admin menu (i don't know any) or is this just for data encryption purposes?

Yes, it's just used to encrypt session data. There's no hidden admin menu at the moment.

**Comment by famaia** [comment]
![image](https://user-images.githubusercontent.com/736407/225994565-15c50ca9-99a8-43d3-980c-d98fe91eca6e.png)

😊
