### ISSUE TITLE
Request for event creator control

### ISSUE THREAD

**Issue by TasneemHardie** [lukevella/Rallly#60]
I want to be able to send out my link and allow collaborators 
- to add their dates in and comments in but **not be able to edit others comments or selection** 
- and also **not be able to edit the details** 

this would make it less stressful wether people are editing it or not.

**Comment by jgreidy** [comment]
A collaborator can also delete the poll - not so good.

**Comment by lukevella** [comment]
I'll be working towards more fine grain permissions in the future. The new version moves one step towards by offering independent links for admins and participants but I will build on top of this to allow for more control in the future.
