### ISSUE TITLE
Installation fails due to missing binding

### ISSUE THREAD

**Issue by anotherdevs** [lukevella/rallly#68]
Hi @lukevella 

> node-sass@3.13.1 install /var/www/doodle/Rallly/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/linux-x64-72_binding.node": 

HTTP error 404 Not Found

This causes it to fail installation:

binding.target.mk:127: recipe for target 'Release/obj.target/binding/src/create_string.o' failed
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
make: Leaving directory '/var/www/doodle/Rallly/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/var/www/doodle/Rallly/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.18-15-pve
gyp ERR! command "/usr/bin/node" "/var/www/doodle/Rallly/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/doodle/Rallly/node_modules/node-sass
gyp ERR! node -v v12.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-25T18_56_29_393Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rallly@1.0.0 installation: `npm i -q && npm run config -- -f`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rallly@1.0.0 installation script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-25T18_56_29_468Z-debug.log

**Comment by stackedsax** [comment]
@anotherdevs you need to use node 7.x.  

Looks like you're using npm 12.x.  You can see that the binary it's trying to download is node module "72".  However, for the v3.13.1 release of node-sass, there is no binary that matches: 

 * https://github.com/sass/node-sass/releases/tag/v3.13.1

The highest node module version that I see on those binaries for 3.13.1 is 51.  That correlates to node 7.

Use nvm to install node 7 and you'll have better luck with the `npm install`.

**Comment by anotherdevs** [comment]
@stackedsax Interesting, however the Dockerfile doesn't work either.

**Comment by lukevella** [comment]
Sorry I was not able to offer support. A new version has been released and the old version has been deprecated. Closing this issue.
