### ISSUE TITLE
[Contribution] Add contribution to documentation in contributing file

### ISSUE THREAD

**Issue by Dynnammo** [lukevella/rallly#684]
Currently, as  a developer, if I spot a mistake in the documentation, I must use Discord or the main Rallly repo issues to inform about it.

It'll be great to have : 
- a paragraph in the contributing file that point to the documentation repository
- on the documentation website, a link pointing to this documentation repository, maybe in the form of a section after/before "Become a contributor"

**Comment by lukevella** [comment]
Thanks @Dynnammo. The support docs are in the [main repo](https://github.com/lukevella/rallly/tree/main/apps/docs) as well now so raising issues here would be best. But you're totally right I should include more information on how to contribute to these docs. I'll work on that this week, thanks for raising.
