### ISSUE TITLE
Add the possibility to change response texts/add options

### ISSUE THREAD

**Issue by wildy** [lukevella/rallly#689]
Hi,

I would like to see the possibility to change response texts from the default (Yes/No/If needed) to something else, or even add new options. The 'if needed' answer is confusing to people -- I would probably rename it to 'Not sure', or something similar.

A possibility to add custom responses would be awesome as well.

**Comment by lukevella** [comment]
I understand the desire for this but at the moment, I don't see a way this can be implemented without adding a lot of complexity to the codebase and UI. Maybe in the distant future.
