### ISSUE TITLE
Magic Links in login mails use insecure http instead of https as configured

### ISSUE THREAD

**Issue by sjansen1** [lukevella/rallly#691]
**Describe the bug**
New install of v.2.11.0 with docker-compose, after configuring e-mail settings and URL to NEXT_PUBLIC_BASE_URL=https://myserver.com , i was surprised that the magic link in the login mail appear as "http://myserver.com/auth/login?token=...". It looks like the https from config.env is not carried over.

From a security standpoint, it is not great to transfer tokens over http, i am quiete sure this is a bug.

**Comment by lukevella** [comment]
Can't reproduce and I don't any path to this happening. There's no modification of `NEXT_PUBLIC_BASE_URL` when generating the magic link. Try rebuilding your container. It's likely that you've built the container with `http` and then changed `config.env` after without rebuilding.
