### ISSUE TITLE
Authentication with oauth

### ISSUE THREAD

**Issue by kolaente** [lukevella/rallly#697]
It would be very cool if rallly provided a way to authenticate using a third party auth provider using the oauth / openid protocol.

**Comment by icsy7867** [comment]
Seconded - OIDC, SAML, Or HTTP Header authentication would be great.

**Comment by mpldr** [comment]
Thirded and adding that OIDC is probably relatively easy to implement using an existing library for it, if one does know JS and how OAuth works. I do not know JS, unfortunately.

**Comment by lukevella** [comment]
First step is to start using next-auth. However it doesn't have any providers that support anonymous/guest sessions so will likely need to roll our own and we'll need to make ensure compatibility with the existing sessions so that existing guests don't get locked out of their polls or responses.

**Comment by mpldr** [comment]
> However it doesn't have any providers that support anonymous/guest
> sessions so will likely need to roll our own and we'll need to ensure
> compatibility with the existing sessions

Again, I may be showing my ignorance on how the JS-crowd does things, so
bear with me :D

Right now users have a token of some kind that identifies them as the
owner/administrator of a poll. If someone with such a token signs in
through an SSO provider, the identifier and the account it should be
linked to are known, so would it not be easy™ to migrate polls to the
newly created account?

Go-ey pseudocode:

```
if cookies.IsSet("account-cookie") && cookies.IsSet("guest-session") {
	database.ChangeOwner(cookies.Get("guest-session"), cookies.Get("account-cookie"))
	cookies.Delete("guest-session")
}

var activeIdentity uuid.UUID

if cookies.IsSet("account-cookie") {
	activeIdentity = cookies.Get("account-cookie")
}

if cookies.IsSet("guest-session") {
	activeIdentity = cookies.Get("guest-session")
}

// do permission stuff and the like
```

Again, as I am not a JS dev and rather unfamiliar with the codebase,
I can only act as somewhat of a rubber-duck here. Feel free to use me
for that purpose though, if you so desire :D

-- 
Moritz Poldrack
https://moritz.sh

> Breaking seal constitutes acceptance of agreement.

**Comment by lukevella** [comment]
I wasn't referring to migrating polls from guests to users. Even more basic then that, changing how authentication works could invalidated all sessions. That means:

* Everyone will be logged out (not a big deal, just log in again)
* All guest session will be renewed

That last one is a problem because many users rely on these guest sessions to have access to the polls and responses they have created. So we either need to have the new auth provider recognize these old sessions or have a plan to migrate them. That's not easy. These sessions are in user's browsers not in our database. It's a solve-able problem but it's not something that can be rushed or hacked as a mistake could be quite costly.

**Comment by mpldr** [comment]
Why would changing the authentication method concern token validity at
all? Wouldn't it just add a new way of authenticating? At least I don't
see a reason to invalidate any session. Or are the tokens assigned by
the auth library?

-- 
Moritz Poldrack
https://moritz.sh

> Opened for inspection.

**Comment by Divin-18** [comment]
u can use clerk auth   Link-https://clerk.com/docs/quickstarts/nextjs

**Comment by troplin** [comment]
@lukevella this is already in version 3.4 that is published on docker hub, right?

Somehow I'm unable to activate OIDC, it's not even showing the additional button on the login page.
There's also nothing in the log at all.

Is there a way to debug this, e.g. change the log level?

**Comment by mpldr** [comment]
Glad it's not just me…

**Comment by lukevella** [comment]
Ok sorry guys, it looks like the issue is that the login page was being statically rendered during build time when the required env variables are not present. I'm going to release a patch to make sure this is rendered dynamically which will fix this issue.

**Comment by mpldr** [comment]
Works as advertised. Thanks for the quick fix ;)
