### ISSUE TITLE
Invitees aren't receiving invite emails

### ISSUE THREAD

**Issue by jacobshare** [lukevella/Rallly#70]
Hi
I created an event yesterday with 3 other participants. At least one of them confirmed that they still haven't received the invite email in their Gmail account, including in their Spam folder.

Anyone else confirm this?

thanks

Jacob

**Comment by lukevella** [comment]
I believe this was due to an attack on the site that spammed our email service and used up our monthly quota. This has since been resolved.

**Comment by jacobshare** [comment]
Thanks 👍
