### ISSUE TITLE
Update support docs with new screenshots

### ISSUE THREAD

**Issue by lukevella** [lukevella/rallly#716]
The pages in our [support docs](https://support.rallly.co/introduction) still use screenshots from v2. We should update the screenshots along with the instructions to match more closely with what's in v3.

The pages that need to be updated are the [guides for administrators](https://github.com/lukevella/rallly/tree/main/apps/docs/administrators) and [guides for participants](https://github.com/lukevella/rallly/tree/main/apps/docs/participants)

If anyone wants to help with this it would be great. The docs are hosted in this repo in the [apps/docs](https://github.com/lukevella/rallly/tree/main/apps/docs) directory. Instructions to run the docs locally are in the README.

**Comment by sha0urya** [comment]
sir.. i want to work on this. Can you please assign me.

**Comment by gyancodes** [comment]
@lukevella Can you assign me this issue?
