### ISSUE TITLE
UX problems - bad user experience

### ISSUE THREAD

**Issue by port22** [lukevella/Rallly#73]
I'd really like to use the app, if some ux issues could be fixed:

- the Save button on the far-right side is out of reach when you have more than 7 dates. The save button should be outside of this area, more at the bottom OR at the most-left, before the name. Or even better, no save button at all. Instant-save any action.
- why is the div class=box fixed at 800px? with more than 7 dates you have to scroll horizontally, which sucks. And which is the reason I was searching the save button more than 10sec until I found I have to scroll to the right. I did not have any issues deleting the width-property or setting it to 100%
- doodle gives you the ability to double-click a date for an option saying "Yes, if need be". If not applicable in the one checkbox, just provide another
- provide the ability to let users add/suggest another date. That one is crucial!

Anyway, by far my most favorite out there!

**Comment by lukevella** [comment]
Thanks for the feedback @port22. I agree with all the points above and I'm currently working on a new version of Rallly that will address these issues. Stay tuned.
