### ISSUE TITLE
[UI] Pricing card top hides under the header

### ISSUE THREAD

**Issue by gyancodes** [lukevella/rallly#735]
**Describe the bug**
The pricing card  top hides under the header

**To Reproduce**

1. Go to 'created poll (free)'
2. Click on 'Finalize from the right  top menu'
4. See the error
[](url)

**Screenshots**
![error](https://github.com/lukevella/rallly/assets/61907167/5fe99689-1fd0-40f9-9ac7-2ed3ed737cf0)

**Expected behavior**

The card needs to have a margin from top
![error](https://github.com/lukevella/rallly/assets/61907167/665064e0-bd98-45d7-898c-15221dbbb917)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [chrome]

**Comment by gyancodes** [comment]
@lukevella Can I work on this issue.

**Comment by lukevella** [comment]
My opinion: It's fine. It won't be like this forever. Not worth spending time on. Closing.
