### ISSUE TITLE
Docker: various errors

### ISSUE THREAD

**Issue by RaitoBezarius** [lukevella/rallly#74]
Thank you for this project, it looks super interesting.

I'm trying to selfhost an instance using Docker and I met some errors:

(1) When using the `docker-compose.yml`, the `.` folder is mounted, why? It causes permissions errors with NPM/Node.js and ultimately creates failure.

(2) Fixing this issue, I find this deprecation warning: `app_1  | (node:28) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client` among various high/medium security warnings regarding your dependencies (mongodb, handlebars, etc.)

(3) Then I have this SSL/TLS issue which I'm not sure how to debug: `app_1  | Sun, 08 Dec 2019 23:24:51 GMT rallly Error: 140096987851592:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:` it could be related to the SMTP server I suppose or because I'm setting Rallly in a reverse proxy fashion with SSL termination being done by NGINX.

(4) The worst one is: `app_1  | Sun, 08 Dec 2019 23:24:51 GMT rallly connection error { MongoError: failed to connect to server [undefined:27017] on first connect [MongoError: getaddrinfo ENOTFOUND undefined undefined:27017]` even though `.env` is correctly set up AFAIK, in the container, I can resolve `db` to an IP address, so I'm unsure what's the problem.

If someone can guide me a it on what should I expect from (3) and (4), I can send a PR to fix some issues.

EDIT: For some reason, in the container, `config.json` is empty even though I pass a full featured and complete `.env`, I regenerated inside the container, the website is working though it seems like SMTP_SECURE being true does not work very well with STARTTLS.

**Comment by lukevella** [comment]
Sorry I was not available to offer support for this. A new version has been released and the old version has been deprecated. Closing this issue since it relates to the old version.
