### ISSUE TITLE
Error starting up locally

### ISSUE THREAD

**Issue by kleenkanteen** [lukevella/rallly#761]
**Describe the bug**
Initially my typescript version was wrong, a bit higher than the workspace version. But I changed it to the workspace version and still get the same errors.

I get these 2 errors when running `yarn dev`. Here is the terminal output of the first error:

![image](https://github.com/lukevella/rallly/assets/67878058/66f2c6df-f441-4d97-9b1c-94f786fa33e4)

Here is the second error:

![image](https://github.com/lukevella/rallly/assets/67878058/17f54b05-836d-49ff-b45f-0856c3e759f5)

I created a "static" folder under rallly\packages\emails\src\templates\ and reran `yarn dev` but same issue.

Here is the full terminal output with both errors. The first one starts 1/5th of the way down, with the command being "email dev --port 3333 --dir ./src/templates". The second error starts 3/5th of the way down with "TypeError [ERR_INVALID_URL]: Invalid URL":
![image](https://github.com/lukevella/rallly/assets/67878058/559d615f-4528-4384-9690-ef2462162d52)

**To Reproduce**
1. Follow the development guide on the readme.
2. At the step `yarn dev`, I get this error.

**Expected behavior**
@rallly/emails:dev server and @rallly/landing:dev server to start up normally.

**Screenshots**
For the error saying `@rallly/landing:dev: TypeError [ERR_INVALID_URL]: Invalid URL`, here is the line of code it seems to break on, line 49:

![image](https://github.com/lukevella/rallly/assets/67878058/47ed1517-a4df-45ef-8a4d-b7ee372885b3)

File: rallly\apps\landing\next.config.js:49:22

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: none so far
 - Version: 2H22, latest version

**Additional context**

**Comment by kleenkanteen** [comment]
For the email issue, this is a related issue to my problem: https://github.com/resendlabs/react-email/issues/613

**Comment by lukevella** [comment]
Any idea if updating react-email fixes this?

**Comment by kleenkanteen** [comment]
react-email was on the latest version, 1.9.4.

I tried setting up rallly on WSL, but I couldn't get WSL to connect to postgres on the host windows.

I then installed Kubuntu in a VM. I followed the developement guide. Then at yarn dev, I get pretty the same 2 errors I got on windows:

![image](https://github.com/lukevella/rallly/assets/67878058/8ac61d0d-3a58-46b6-b72e-c35a85a8549e)

I think the URL error is due to rallly uses the next.js pages router, which is before version 13 but the version in package.json uses 13+.

The email one I have no idea, I think it's because the latest react-email package has an issue. I will try with an older version.

Going to try both now.

**Comment by kleenkanteen** [comment]
Downgrading react-email in rallly/packages/emails/package.json to [1.7.15](https://www.npmjs.com/package/react-email/v/1.7.15) does the trick for the second error.

For the invalid URL issue, downgraded "next" package to 12.2.6 in rallly/package.json. Error persists.

**Comment by kleenkanteen** [comment]
@lukevella Found the cause of the invalid URL error. In sample.env, the variable NEXT_PUBLIC_BASE_URL does not match the variable referenced in apps/landing/next.config.js. In this file it is NEXT_PUBLIC_APP_BASE_URL instead, the APP part shouldn't be there.

**Comment by lukevella** [comment]
Those are two different variables. 

`NEXT_PUBLIC_APP_BASE_URL` is https://app.rallly.co in production. This is internal config only used to set the redirects  from the landing page.

**Comment by lukevella** [comment]
I think the simplest solution is to add `NEXT_PUBLIC_APP_BASE_URL` to `sample.env` and set it to `http://localhost:3000`. `NEXT_PUBLIC_BASE_URL` should be different for each app, i.e. (port 3001 for the landing page and port 3000 for the app).

**Comment by kleenkanteen** [comment]
Ok makes sense. Should I make a PR adding NEXT_PUBLIC_APP_BASE_URL to the sample.env?

**Comment by kleenkanteen** [comment]
Can I also add in the PR the change to react-email to fix it to version 1.7.15?

**Comment by lukevella** [comment]
Unless they are related somehow I'd keep them in separate PRs.

Feel free to add `NEXT_PUBLIC_APP_BASE_URL` to `sample.env`. Thanks for spotting that, I hadn't noticed this issue since that var was configured locally.
