### ISSUE TITLE
Table is misaligned

### ISSUE THREAD

**Issue by prampec** [lukevella/Rallly#8]
Dates are misaligned with the table content if Firefox as seen on the screenshot.
![screen shot 2015-07-21 at 22 34 05](https://cloud.githubusercontent.com/assets/10376327/8811817/b40ef74a-2ff8-11e5-8d8c-0bd61a6b6230.png)
In style.css line 6 the min-width of ".poll-body .poll-entry .cell.vote-cell" is 70px however a value 50px seems to fit better for me.

**Comment by lukevella** [comment]
Thanks for pointing this out. Will try to release a fix asap.
