### ISSUE TITLE
FindTime style behavior

### ISSUE THREAD

**Issue by cha0sg0d** [lukevella/rallly#81]
Outlook has a built in [feature](https://findtime.microsoft.com/) where times can be recommended based on the participants calendar. 

I think it's about time that there is an open source version of this that can work across calendars (Google, Outlook, etc.). 
Participants would enter their calendar and a list of times that work for everyone would be automatically generated, then sent out as a Rallly event.

I am a full-stack developer and I would be very interested in collaborating on this project.

**Comment by lukevella** [comment]
Thanks for your suggestion and sorry it's taken me so long to reply. I'm only just refocusing my efforts on this project. I'm going to have to say that this is currently out of scope but wouldn't exclude taking Rallly in to this space in the future.
