### ISSUE TITLE
Make it possible to have a constantly running planner that people can mark of. (For rpg meetings :P )

### ISSUE THREAD

**Issue by DipsoNOR** [lukevella/rallly#83]
We have been using doodle for a while to find out when our next rpg meeting is going to be, but it doesn't quite satisfy our needs, and are looking for alternatives, but currently all tools have the same problems or are just not usable.

The biggest "problem" we have is that we want it to be a constantly running thing that people can fill  in as they know how their days look ahead.

For that we need a planner that is "open" from the current date forward at all times.

It would also be nice if it could differentiate between "non-answered" dates and dates actively set as available, maybe or busy.

I think that would be a way to differentiate this tool from others like it, if it accommodated different ways to meet, because now most tools assume that you have a specific or limited time frame, but i suspect more people are like us, who just want to map out what days they can meet either physically or these days, virtually.

**Comment by lukevella** [comment]
Thanks for the suggestion. I think this is a nice idea but a bit out of scope at the moment. I wouldn't exclude supporting this use case in the future.
