### ISSUE TITLE
Dockerfile: no such file or directory

### ISSUE THREAD

**Issue by nirurin** [lukevella/rallly#845]
**Describe the bug**

[+] Building 0.2s (2/2) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 2B                                                                                 0.0s
 => [internal] load .dockerignore                                                                                  0.2s
 => => transferring context: 35B                                                                                   0.0s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /volume3/@docker/tmp/buildkit-mount3718834270/Dockerfile: no such file or directory

**To Reproduce**
1. Try and build using 
sudo docker-compose -p "rallly" up -d

**Expected behavior**
Not throwing an error lol

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by lukevella** [comment]
Hi @nirurin, I wasn't able to reproduce this. It appears like the problem could be unrelated to this repo so I'll be closing this issue. Thanks.
