### ISSUE TITLE
Allowed email not matching as expected

### ISSUE THREAD

**Issue by sir-andreas** [lukevella/rallly#859]
When I try to register a new user the system declines that with "email not allowed". (but I allowed this email in the config file, of course)
Is there any chance to find out, whats the problem with that?

**Comment by sir-andreas** [comment]
Thank you, that fixed my issue as well. 

Best regards!

**Comment by lukevella** [comment]
Oh cool. Are you building the project from the source code then?

**Comment by sir-andreas** [comment]
Yes, I corrected it directly in the source code since it was only this one line changed.

**Comment by lukevella** [comment]
Ah ok. Great thanks for confirming.
