### ISSUE TITLE
Deleting polls 

### ISSUE THREAD

**Issue by fdecourt** [lukevella/rallly#876]
**Describe the bug**
On the v3 (migrated from v2) version, when deleting a Poll : 

![image](https://github.com/lukevella/rallly/assets/4050977/eef38635-3b17-409c-9c5d-ba3507cd5067)

The text to enter is not shown, and there is no field to to so. But it is still possible to delete the poll.

Regards,

**Comment by lukevella** [comment]
Thanks for reporting. I think we just need to change the key to invalidate the translation in Crowdin.

**Comment by lukevella** [comment]
Fixed in #875. New translations are still pending.
