### ISSUE TITLE
No way to modify votes/log in again via invite link

### ISSUE THREAD

**Issue by ltguillaume** [lukevella/rallly#882]
**Describe the bug**
If someone revisits a poll via the invite link, there is no clear way to log in again.

**To Reproduce**
1. Click an invite link, fill in the poll and register
2. Clear cookie/use different browser/device
3. Click the invite link again
4. Don't see any way to log in and change your votes

**Expected behavior**
See a "Log in" button which takes you to through the login process _and then redirects back to the poll_.

v3.1.0

**Comment by lukevella** [comment]
Thanks for raising. I'll be looking to address this soon.

**Comment by lukevella** [comment]
I'll try and have a version out this week that addresses this.

**Comment by lukevella** [comment]
Sorry for the delay, been dealing with other issues this week. I do have a release candidate ready to go but probably not gna ship today being a Friday and all. If you want to test it out, it's published on docker hub with the tag `3.2.0-rc1`.

**Comment by lukevella** [comment]
> For a user
Even though I'm now logged in as a user:
>
> Clicking [Continue] still asks me for a new name and email
If the now logged in user created this poll, it still doesn't get access to the poll settings
Solution: redirect from .../invite/... to .../poll/... automatically if the user who just logged in is the owner of the poll

Understandable but plenty of people rely on the flexibility of being able to add multiple participants. That said I do plan to address this but it sits at a low priority right now.

> For a participant
It is still not possible to log in and change your votes at all. While I get the distinction between user and participant, this is found very confusing by the users.

Did upgrading to 3.2.1 fix this for you?

**Comment by lukevella** [comment]
You still need to register an account with an email address before you can log in. Submitting a response with an email address doesn’t create an account.
