### ISSUE TITLE
UX pb: "Save" button not visible

### ISSUE THREAD

**Issue by ghost** [lukevella/Rallly#9]
I just discovered Rallly, it's awesome and design is much better than Doodle. Here is a fast feedback.

I see just one problem: the "Save" button is hidden when you pick a lot of date options (because you have to go to the last option to see it) => for average people (which are not used to web tools), it's a big problem because they can forget to slide right and therefore, to save.
I think it would be much better to place it under the table...

Thank you!
Camille

**Comment by lukevella** [comment]
New version fixes this.
