### ISSUE TITLE
two different people seeing different dates marked

### ISSUE THREAD

**Issue by austin-l-a** [lukevella/rallly#90]
We have 4 people who entered into the poll and all are in different time zones. 3 people showed tuesdays being marked and 1 person showed mondays being marked resulting in a mis-scheduled meeting.

![thumbnail_image001](https://user-images.githubusercontent.com/58946500/114737557-c0845b00-9d0c-11eb-811a-1227945ca2ca.png)
![image002](https://user-images.githubusercontent.com/58946500/114737715-e7db2800-9d0c-11eb-93eb-1ea0c8535e84.png)

**Comment by austin-l-a** [comment]
Upon further review. It's like it's showing the wrong dates to one person.

**Comment by lukevella** [comment]
This has been resolved in the new version. Polls created with the old version will still have the same issue however due to the way the date values were being stored.
