### ISSUE TITLE
'command not found: prisma ERROR: "db:deploy" exited with 127.' on running "yarn db:setup" command

### ISSUE THREAD

**Issue by 18feb06** [lukevella/rallly#930]
**Describe the bug**
'command not found: prisma ERROR: "db:deploy" exited with 127.' on running "yarn db:setup" command

**To Reproduce**
1. Clone repo and run yarn (to install all dependencies).
2. Configure .env file.
3. run 'yarn db:setup' for setting.
4. See error 'command not found: prisma ERROR: "db:deploy" exited with 127.'

**Expected behavior**
Should start migrations.

**Screenshots**
![Screenshot from 2023-11-07 03-38-04](https://github.com/lukevella/rallly/assets/88766161/255333ba-ceab-4303-8565-14a8a0411211)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser chrome

**Comment by 18feb06** [comment]
@lukevella Can i work on it? I would love to solve this. 😊

**Comment by lukevella** [comment]
I can't reproduce this. The steps work as expected for me. You're welcome to spend as much time as you like trying to fix this.
