### ISSUE TITLE
Created poll not displayed due to wrong JS url

### ISSUE THREAD

**Issue by wneessen** [lukevella/rallly#933]
**Describe the bug**
When I create a new poll, once I submit and the poll is tried to be opened, all I get is a blank page. Looking at the Firefox devtools the console throws an error about not being able to load JS due to a a `[urlId]` in the URL.

**To Reproduce**
1. Go to the Rallly URL
2. Create a new Poll
3. Select all options
4. Submit
5. Being forward to the actual poll URL
6. Blank page is display with the error above

**Expected behavior**
The poll should be displayed

**Screenshots**
![image](https://github.com/lukevella/rallly/assets/542696/6caf6230-cec6-4929-8ebd-5c6305d935bc)

**Desktop (please complete the following information):**
 - OS: macOS X 14.1
 - Browser Firefox
 - Version 119.0

**Additional context**
Running Rallly in a selfhosted environment using the :latest docker image. Migrations are all fine but for testing purpose I deleted the full database and rerun the migrations from scratch - without issues.

**Comment by wneessen** [comment]
I just updated the docker image to the latest version, which seems to have fixed the issue. The polls are now shown correctly.

**Comment by lukevella** [comment]
@wneessen Thanks for checking. Not sure what fixed it but glad the update resolved it for you.
