### ISSUE TITLE
6-digit code appears to fail

### ISSUE THREAD

**Issue by cliff1976** [lukevella/rallly#959]
**Describe the bug**
The 6-digit verification code I got returns an error just seconds after I received it via email.

**To Reproduce**
1. Go to your instance, enter the email address for logging in
2. Receive the 6-digit verification code
3. Observe the error in the screenshot further below
4. Manually edit the URL in the address bar to the base URL for the app, and from there, everything works OK again

**Expected behavior**
I thought copy/pasteing the 6-digit verification code would let me in, like it did before my upgrade to v3.4.2.

**Screenshots**
![image](https://github.com/lukevella/rallly/assets/1834094/6f86d8d0-5225-4963-8471-8925e3ff95f7)

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Browser Firefox
 - Version 120

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: 17-something
 - Browser DuckDuckGo
 - Version 7.97.2

**Additional context**
The 6-digit verification codes worked fine before my recent upgrade from 2.x to 3.4.2.

**Comment by lukevella** [comment]
> Manually edit the URL in the address bar to the base URL for the app, and from there, everything works OK again

Bit confused by this. Can you clarify what you mean here? If you are accessing the app through a URL other than what's configured with `NEXT_PUBLIC_BASE_URL` then it is expected that it will fail.

**Comment by cliff1976** [comment]
I meant exactly the value `NEXT_PUBLIC_BASE_URL`, but your question helped me find the problem.  Thanks.  It's working now.

In the `config.env` file my `NEXT_PUBLIC_BASE_URL` value had the wrong scheme (`http://` vs. `https://').  I think that was left over from my initial setup and it didn't used to inhibit my login.  I'll write something similar on the other bug I submitted, too.

**Comment by lukevella** [comment]
Ah right that makes sense. Thanks for letting me know 👍
