### ISSUE TITLE
OIDC and ADFS Not working

### ISSUE THREAD

**Issue by icsy7867** [lukevella/rallly#961]
**Describe the bug**
When trying to connect to OIDC via my companies ADFS SSO system, I am getting an error

```
Unknown argument `resource`. Available options are listed in green.
    at yn (/app/node_modules/@prisma/client/runtime/library.js:116:5852)
    at wn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6429)
    at wn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6119)
    at wn.request (/app/node_modules/@prisma/client/runtime/library.js:123:5839)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:128:9763) {
  name: 'LinkAccountError',
  code: undefined
```
**To Reproduce**

1. Setup OIDC using ADFS
2. Give the web app access to email, profile and oidc scopes
3. Plug in the values to the app
4. After clicking on the SSO button, and going through the login process, you are brought back to the initial login page.

**Expected behavior**
To be able to successfully log into the app.

**Additional context**
```
OIDC_NAME="My SSO Login"
OIDC_DISCOVERY_URL='https://my.company.com/.well-known/openid-configuration'
OIDC_CLIENT_ID=some-id-here
OIDC_CLIENT_SECRET=XXXXXXXXXXXXXXXX
```

And int he logs:
```
Unknown argument `resource`. Available options are listed in green. PrismaClientValidationError:
Invalid `prisma.account.create()` invocation:

{
  data: {
    provider: "oidc",
    type: "oauth",
    providerAccountId: "redacted",
    access_token: "redacted",
    token_type: "bearer",
    expires_at: 1701984504,
    resource: "redacted",   (Adding a note here - This is the same the app ID or OIDC ID)
    ~~~~~~~~
    refresh_token: "redacted",
    refresh_token_expires_in: 23681,
    scope: "profile email openid",
    id_token: "redacted",
    userId: "redacted",
?   id?: String,
?   session_state?: String | Null
  }
}

Unknown argument `resource`. Available options are listed in green.
    at yn (/app/node_modules/@prisma/client/runtime/library.js:116:5852)
    at wn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6429)
    at wn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6119)
    at wn.request (/app/node_modules/@prisma/client/runtime/library.js:123:5839)
    at async l (/app/node_modules/@prisma/client/runtime/library.js:128:9763) {
  name: 'LinkAccountError',
  code: undefined
}
```

Now interestingly enough, if I take the ID token and decode it I get:

```
{
  "aud": "redacted",
  "iss": "https://sso.my.company.com/adfs",
  "iat": 1701980902,
  "nbf": 1701980902,
  "exp": 1701984502,
  "auth_time": 1701961385,
  "mfa_auth_time": 1701961391,
  "sub": "redacted",
  "upn": "username@my.company.org",
  "unique_name": "...",
  "pwd_exp": "....",
  "sid": "S-1-5-21-...",
  "email": "First.Last@my.company.com",
  "apptype": "Confidential",
  "appid": "redacted",
  "authmethod": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
  "ver": "1.0",
  "scp": "profile email openid"
}
```

So I am not sure why next auth cares about some random key/value in the response.  This probably has more to do with the relationship between ADFS/OIDC and Next-auth than it does your APP, but i was hoping someone could share some insight or maybe I would get lucky.

**Comment by lukevella** [comment]
I think this could be related to #949. I'm hoping there is a fix that would ensure support for all identity providers that follow the OIDC spec but I'm not sure whether this is actually possible or even the right approach. I would like to avoid having to modify the Prisma adapter with exceptions for various providers.

Would be great to get some help from someone with a deeper understanding of this topic.

**Comment by icsy7867** [comment]
Thanks for the reply!  I'll keep an eye on that issue as well.

Great app though!  Thank you for making it.  Feel free to close this if you feel it's superfluous

**Comment by icsy7867** [comment]
Out of curiousity, is PrismaClientValidationError mad because it has extra key->value pairs that it doesnt know what to do with?

Doing some googling:
https://github.com/prisma/prisma/issues/5220
https://stackoverflow.com/questions/71101647/how-to-ignore-extra-fields-when-storing-prisma-data

Instead of writing custom Prisma adapters for every scenario, why dont you just go through the key/values, grab the ones you need, and make a new object without the superfluous field(s)?

Especially since that field does not seem useful in this use case.

**Comment by lukevella** [comment]
> Out of curiousity, is PrismaClientValidationError mad because it has extra key->value pairs that it doesnt know what to do with?

Yes, that does appear to be the problem on the surface.

> Instead of writing custom Prisma adapters for every scenario, why dont you just go through the key/values, grab the ones you need, and make a new object without the superfluous field(s)?
> 
> Especially since that field does not seem useful in this use case.

Well, making this change will require writing a custom prisma adapter but the real issue is that assuming all fields outside the schema are superfluous could be a mistake. I suppose it could be worth making a build with this change and then just see if it works.

**Comment by lukevella** [comment]
Hi @icsy7867, I'm going to close this issue since its likely the same issue as in #949. If you can test out the image `lukevella/rallly:3.5.0-rc1` and let me know if this fixes the issue for you that would be greatly appreciated. Thanks!
