### ISSUE TITLE
New users must register first even if using OIDC

### ISSUE THREAD

**Issue by icsy7867** [lukevella/rallly#986]
**Describe the bug**
Perhaps this is working as intended.  But if a new user tries to log in using OIDC, their auth will fail, unless they have registered for a new account.

(Btw, thank you for the newest version! It's nice having OIDC working with ADFS at all :D 
**To Reproduce**

1. Ask a new user to go to rallly and click the OIDC login button.
2. The login will fail.  Logs state "Argument `name` is missing."

**Expected behavior**
A new user using OIDC should simply be able to log in using OIDC without manually having to register first.

**Additional context**
This might be an issue with ADFS's implementation, or perhaps manually registering first is working as intended?

Full error from docker logs:
```
Argument `name` is missing. {
  message: '\n' +
    'Invalid `prisma.user.create()` invocation:\n' +
    '\n' +
    '{\n' +
    '  data: {\n' +
    '    email: "<redacted>",\n' +
    '    emailVerified: null,\n' +
    '+   name: String\n' +
    '  }\n' +
    '}\n' +
    '\n' +
    'Argument `name` is missing.',
  stack: 'PrismaClientValidationError: \n' +
    'Invalid `prisma.user.create()` invocation:\n' +
    '\n' +
    '{\n' +
    '  data: {\n' +
    '    email: "<redacted>",\n' +
    '    emailVerified: null,\n' +
    '+   name: String\n' +
    '  }\n' +
    '}\n' +
    '\n' +
    'Argument `name` is missing.\n' +
    '    at yn (/app/node_modules/@prisma/client/runtime/library.js:116:5852)\n' +
    '    at wn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6429)\n' +
    '    at wn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6119)\n' +
    '    at wn.request (/app/node_modules/@prisma/client/runtime/library.js:123:5839)\n' +
    '    at async l (/app/node_modules/@prisma/client/runtime/library.js:128:9763)',
  name: 'PrismaClientValidationError'
}
```

P.S - If OIDC is enabled, can we disable email authentication?

**Comment by lukevella** [comment]
It looks like the profile returned by your identity provider does not include the `name` field. I'm assuming it returns an alternative field like `given_name`. I just release [v3.5.1](https://github.com/lukevella/rallly/releases/tag/v3.5.1) to try and address this. Can you give it a try and let me know if it works for you?

**Comment by troplin** [comment]
Actually, some OIDC providers don’t support the `profile` scope at all. E.g. Synology SSO Server which I‘m using. The issue just haven‘t come up yet.

Maybe just make the field optional? The users can change it later in the settings anyway.

**Comment by lukevella** [comment]
> Actually, some OIDC providers don’t support the `profile` scope at all. E.g. Synology SSO Server which I‘m using. The issue just haven‘t come up yet.
> 
> Maybe just make the field optional? The users can change it later in the settings anyway.

@troplin I imagine it will fail earlier with a different error if the profile scope is missing so it would require a bit more than making the field optional. Can you can confirm what error you see and open a new issue if it's different than this one?

**Comment by icsy7867** [comment]
You are so quick to respond thank you! I am still getting the same error:

```
[next-auth][error][adapter_error_createUser]
https://next-auth.js.org/errors#adapter_error_createuser
Invalid `prisma.user.create()` invocation:

{
  data: {
    email: "<redacted>",
    emailVerified: null,
+   name: String
  }
}

Argument `name` is missing. {
  message: '\n' +
    'Invalid `prisma.user.create()` invocation:\n' +
    '\n' +
    '{\n' +
    '  data: {\n' +
    '    email: "<redacted>",\n' +
    '    emailVerified: null,\n' +
    '+   name: String\n' +
    '  }\n' +
    '}\n' +
    '\n' +
    'Argument `name` is missing.',
  stack: 'PrismaClientValidationError: \n' +
    'Invalid `prisma.user.create()` invocation:\n' +
    '\n' +
    '{\n' +
    '  data: {\n' +
    '    email: "<redacted>",\n' +
    '    emailVerified: null,\n' +
    '+   name: String\n' +
    '  }\n' +
    '}\n' +
    '\n' +
    'Argument `name` is missing.\n' +
    '    at yn (/app/node_modules/@prisma/client/runtime/library.js:116:5852)\n' +
    '    at wn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6429)\n' +
    '    at wn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:123:6119)\n' +
    '    at wn.request (/app/node_modules/@prisma/client/runtime/library.js:123:5839)\n' +
    '    at async l (/app/node_modules/@prisma/client/runtime/library.js:128:9763)',
  name: 'PrismaClientValidationError'
```

Perhaps, if this information is required, simply prompt a new user to fill in the missing field:

![image](https://github.com/lukevella/rallly/assets/3788162/6862a984-1c7b-4fa3-a659-8d29e6d48fa3)

But manually registering first is not the end of the world either.  Thank you for your awesome prompt responses!

**Comment by icsy7867** [comment]
Update - Our auth guys fixed it!  With ADFS they were able to cobble together Given-Name and Surname and made a custom attribute called "name" and this seemed to be accepted!

**Comment by icsy7867** [comment]
ADFS works after manually creating the "name" claim.

**Comment by lukevella** [comment]
@icsy7867 good to know. Thanks for the update.
