### ISSUE TITLE
Sender name cannot be configured

### ISSUE THREAD

**Issue by lukevella** [lukevella/rallly#994]
Currently the sender name is hardcoded to "Rallly". 

See: #992

**Comment by bmaster001** [comment]
Here's a diff file for this (sorry, I'm not sure how to make a pullrequest for this)
[senderemailname.diff.txt](https://github.com/lukevella/rallly/files/14050348/senderemailname.diff.txt)

**Comment by mark-pitblado** [comment]
I was scrolling through the open issues, and believe this one can be closed? Just in case people get confused thinking that sender name isn't currently supported as the release has now happened

**Comment by lukevella** [comment]
@mark-pitblado thanks for reminding me!
